<fildset><legend>FORMULARIO DE MANUTENÇÃO</legend><div class="box&#x20;box-full-12&#x20;box-medium-06&#x20;box-large-08"><div class="widgets-box"><div class="box-header&#x20;box-default"><i class="ion&#x20;ion-clipboard"></i><h3 class="box-title">GERAL</h3></div><div class="box-body"><div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{title}}');?>#title#</div>
<div class="clear"></div></div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{description}}');?>#description#</div>
<div class="clear"></div></div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{alias}}');?>#alias#</div>
<div class="clear"></div></div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{email}}');?>#email#</div>
<div class="clear"></div></div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{facebook}}');?>#facebook#</div>
<div class="clear"></div></div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{twitter}}');?>#twitter#</div>
<div class="clear"></div></div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{phone}}');?>#phone#</div>
<div class="clear"></div></div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{endereco}}');?>#endereco#</div>
<div class="clear"></div></div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{bairro}}');?>#bairro#</div>
<div class="clear"></div></div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{fantasia}}');?>#fantasia#</div>
<div class="clear"></div></div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{cidade}}');?>#cidade#</div>
<div class="clear"></div></div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{longetude}}');?>#longetude#</div>
<div class="clear"></div></div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{latitude}}');?>#latitude#</div>
<div class="clear"></div></div>
#asset_id##empresa##created_by##modified_by##ordering##modified##security#</div><div class="box-footer"><div class="pull-right">#save##save_copy#<a class="btn btn-black" href="/operacional/bs-companies/index">BTN_VOLTAR_LABEL</a><p></div></div></div></div><div class="box&#x20;box-full-12&#x20;box-medium-06&#x20;box-large-04"><div class="widgets-box"><div class="box-header&#x20;box-default"><i class="ion&#x20;ion-clipboard"></i><h3 class="box-title">CONTROLES</h3></div><div class="box-body"><div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{id}}');?>#id#</div>
<div class="clear"></div></div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{codigo}}');?>#codigo#</div>
<div class="clear"></div></div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{state}}');?>#state#</div>
<div class="clear"></div></div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{access}}');?>#access#</div>
<div class="clear"></div></div></div></div></div><div class="box&#x20;box-full-12&#x20;box-medium-06&#x20;box-large-04"><div class="widgets-box"><div class="box-header&#x20;box-default"><i class="ion&#x20;ion-clipboard"></i><h3 class="box-title">IMAGENS</h3></div><div class="box-body"><div class="img-add&#x20;"><?php echo $this->translate('{{images}}');?>#imagePreview#</div>
<div class="row">
<div class="input-group&#x20;class-file"><div class="btn&#x20;btn-blue&#x20;btn-file"><i class="ion&#x20;ion-android-upload"></i><span class="file-text">Selecione uma imagem</span><input name="attachment" type="file" id="attachment" />#images#</div><p class="help-block">Max. 32MB</p></div>
<div class="clear"></div></div></div></div></div><div class="box&#x20;box-full-12&#x20;box-medium-06&#x20;box-large-04"><div class="widgets-box"><div class="box-header&#x20;box-default"><i class="ion&#x20;ion-clipboard"></i><h3 class="box-title">DATAS</h3></div><div class="box-body"><div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{created}}');?><div class="input-group-addon"></div>#created#</div>
<div class="clear"></div></div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{publish_up}}');?><div class="input-group-addon"></div>#publish_up#</div>
<div class="clear"></div></div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{publish_down}}');?><div class="input-group-addon"></div>#publish_down#</div>
<div class="clear"></div></div></div></div></div></fildset>