<div class="box&#x20;box-full-12&#x20;box-mini-06&#x20;&#x20;box-small-06&#x20;box-medium-04&#x20;box-large-04&#x20;col-box-list">
<div class="widgets-box"><div class="box-header&#x20;box-default"><i class="ion&#x20;ion-android-open"></i>
<h2 class="box-title">{{title}}</h2><br /><small class="fl-left">CRIADO EM: {{created}}</small><small class="fl-right"> POR: {{editorBy}}</small></div>
<div class="box-body">
<p class="box-description">
<div class="box-list banco">banco_id: {{banco_id}}</div>
<div class="box-list">tipo: {{tipo}}</div>
<div class="box-list banco">agencia: {{agencia}}</div>
<div class="box-list banco">conta: {{conta}}</div>
<div class="box-list banco">gerente: {{gerente}}</div>
<div class="box-list banco">phone: {{phone}}</div>
<div class="box-list">saldo: {{saldo}}</div>
<div class="box-list">situacao: {{situacao}}</div>
<div class="box-list">description: {{description}}</div>
<div class="box-list">state: {{state}}</div>
<div class="box-list">alias: {{alias}}</div>
</p></div><div class="box-footer">{{buttons}}</div></div></div>