<div class="box&#x20;box-full-12&#x20;box-mini-06&#x20;&#x20;box-small-06&#x20;box-medium-04&#x20;box-large-04&#x20;col-box-list">
<div class="widgets-box">
<div class="box-header&#x20;box-default">
<i class="ion&#x20;ion-android-open"></i>
<h2 class="box-title">{{title}}</h2>
<br />
<small class="fl-left"><?php echo $this->translate('CRIADO EM: ');?>{{created}}</small><small class="fl-right"><?php echo $this->translate(' POR: ');?>{{editorBy}}</small>
</div>
<div class="box-body">
<p class="box-description">
<div class="box-list&#x20;list-empresa"><i class="ico&#x20;ico-empresa"></i><span class="label-list&#x20;label-list-empresa"><?php echo $this->translate('empresa');?> :</span><span class="data-list&#x20;data-list-empresa">{{empresa}}</span></div>
<div class="box-list&#x20;list-conta_tipo"><i class="ico&#x20;ico-conta_tipo"></i><span class="label-list&#x20;label-list-conta_tipo"><?php echo $this->translate('conta_tipo');?> :</span><span class="data-list&#x20;data-list-conta_tipo">{{conta_tipo}}</span></div>
<div class="box-list&#x20;list-banco_id"><i class="ico&#x20;ico-banco_id"></i><span class="label-list&#x20;label-list-banco_id"><?php echo $this->translate('banco_id');?> :</span><span class="data-list&#x20;data-list-banco_id">{{banco_id}}</span></div>
<div class="box-list&#x20;list-tipo"><i class="ico&#x20;ico-tipo"></i><span class="label-list&#x20;label-list-tipo"><?php echo $this->translate('tipo');?> :</span><span class="data-list&#x20;data-list-tipo">{{tipo}}</span></div>
<div class="box-list&#x20;list-agencia"><i class="ico&#x20;ico-agencia"></i><span class="label-list&#x20;label-list-agencia"><?php echo $this->translate('agencia');?> :</span><span class="data-list&#x20;data-list-agencia">{{agencia}}</span></div>
<div class="box-list&#x20;list-conta"><i class="ico&#x20;ico-conta"></i><span class="label-list&#x20;label-list-conta"><?php echo $this->translate('conta');?> :</span><span class="data-list&#x20;data-list-conta">{{conta}}</span></div>
<div class="box-list&#x20;list-gerente"><i class="ico&#x20;ico-gerente"></i><span class="label-list&#x20;label-list-gerente"><?php echo $this->translate('gerente');?> :</span><span class="data-list&#x20;data-list-gerente">{{gerente}}</span></div>
<div class="box-list&#x20;list-phone"><i class="ico&#x20;ico-phone"></i><span class="label-list&#x20;label-list-phone"><?php echo $this->translate('phone');?> :</span><span class="data-list&#x20;data-list-phone">{{phone}}</span></div>
<div class="box-list&#x20;list-saldo"><i class="ico&#x20;ico-saldo"></i><span class="label-list&#x20;label-list-saldo"><?php echo $this->translate('saldo');?> :</span><span class="data-list&#x20;data-list-saldo">{{saldo}}</span></div>
<div class="box-list&#x20;list-situacao"><i class="ico&#x20;ico-situacao"></i><span class="label-list&#x20;label-list-situacao"><?php echo $this->translate('situacao');?> :</span><span class="data-list&#x20;data-list-situacao">{{situacao}}</span></div>
<div class="box-list&#x20;list-description"><i class="ico&#x20;ico-description"></i><span class="label-list&#x20;label-list-description"><?php echo $this->translate('description');?> :</span><span class="data-list&#x20;data-list-description">{{description}}</span></div>
<div class="box-list&#x20;list-ordering"><i class="ico&#x20;ico-ordering"></i><span class="label-list&#x20;label-list-ordering"><?php echo $this->translate('ordering');?> :</span><span class="data-list&#x20;data-list-ordering">{{ordering}}</span></div>
<div class="box-list&#x20;list-state"><i class="ico&#x20;ico-state"></i><span class="label-list&#x20;label-list-state"><?php echo $this->translate('state');?> :</span><span class="data-list&#x20;data-list-state">{{state}}</span></div>
<div class="box-list&#x20;list-created_by"><i class="ico&#x20;ico-created_by"></i><span class="label-list&#x20;label-list-created_by"><?php echo $this->translate('created_by');?> :</span><span class="data-list&#x20;data-list-created_by">{{created_by}}</span></div>
<div class="box-list&#x20;list-modified_by"><i class="ico&#x20;ico-modified_by"></i><span class="label-list&#x20;label-list-modified_by"><?php echo $this->translate('modified_by');?> :</span><span class="data-list&#x20;data-list-modified_by">{{modified_by}}</span></div>
<div class="box-list&#x20;list-alias"><i class="ico&#x20;ico-alias"></i><span class="label-list&#x20;label-list-alias"><?php echo $this->translate('alias');?> :</span><span class="data-list&#x20;data-list-alias">{{alias}}</span></div>
<div class="box-list&#x20;list-modified"><i class="ico&#x20;ico-modified"></i><span class="label-list&#x20;label-list-modified"><?php echo $this->translate('modified');?> :</span><span class="data-list&#x20;data-list-modified">{{modified}}</span></div>
<div class="box-list&#x20;list-publish_up"><i class="ico&#x20;ico-publish_up"></i><span class="label-list&#x20;label-list-publish_up"><?php echo $this->translate('publish_up');?> :</span><span class="data-list&#x20;data-list-publish_up">{{publish_up}}</span></div>
<div class="box-list&#x20;list-publish_down"><i class="ico&#x20;ico-publish_down"></i><span class="label-list&#x20;label-list-publish_down"><?php echo $this->translate('publish_down');?> :</span><span class="data-list&#x20;data-list-publish_down">{{publish_down}}</span></div></p></div>
<div class="box-footer">{{buttons}}</div>
</div>
</div>