<fildset><legend>FORMULARIO DE MANUTENÇÃO</legend><div class="box&#x20;box-full-12&#x20;box-medium-06&#x20;box-large-08"><div class="widgets-box"><div class="box-header&#x20;box-default"><i class="ion&#x20;ion-clipboard">
</i>
<h3 class="box-title">GERAL
</h3>
</div>
<div class="box-body"><div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-07"><?php echo $this->translate('{{title}}')?>#title#</div>
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-05"><?php echo $this->translate('{{conta_id}}')?>#conta_id#</div>
<div class="clear"></div></div>

<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-05"><?php echo $this->translate('{{situacao}}')?>#situacao#</div>
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-07 cl-paga"><?php echo $this->translate('{{repete}}')?>#repete#</div>
<div class="clear"></div></div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-03 cl-paga"><?php echo $this->translate('{{perildo}}')?>#perildo#</div>

<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-02 cl-paga"><?php echo $this->translate('{{qtdade}}')?>#qtdade#</div>

<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-05"><?php echo $this->translate('{{plano_conta_id}}')?>#plano_conta_id#</div>

<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-02"><?php echo $this->translate('{{valor}}')?>#valor#</div>
<div class="clear"></div></div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-04"><?php echo $this->translate('{{centro_custo_id}}')?>#centro_custo_id#</div>

<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-05"><?php echo $this->translate('{{cliente_id}}')?>#cliente_id#</div>

<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-03"><?php echo $this->translate('{{fpgto_id}}')?>#fpgto_id#</div>
<div class="clear"></div></div>

<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{description}}')?>#description#</div>
<div class="clear"></div></div>

<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-04"><?php echo $this->translate('{{tipo_documento}}')?>#tipo_documento#</div>
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-02"><?php echo $this->translate('{{num_documento}}')?>#num_documento#</div>
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-06"><?php echo $this->translate('{{alias}}')?>#alias#</div>
<div class="clear"></div></div>

#asset_id##empresa##created_by##modified_by##ordering##modified##security##caixa_id#
</div>
<div class="box-footer"><div class="pull-right">#save##save_copy#<a class="btn btn-black" href="/fluxo-caixa/bs-contas-receber/index"><?php echo $this->translate('BTN_VOLTAR_LABEL')?></a><p>
</div>
</div>

</div>
</div>

<div class="box&#x20;box-full-12&#x20;box-medium-06&#x20;box-large-04"><div class="widgets-box"><div class="box-header&#x20;box-default"><i class="ion&#x20;ion-clipboard">
</i>
<h3 class="box-title">DATAS/VENCIMENTOS
</h3>
</div>
<div class="box-body"><div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{created}}')?><div class="input-group-addon"></div>#created#</div>
<div class="clear"></div></div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{publish_up}}')?><div class="input-group-addon"></div>#publish_up#</div>
<div class="clear"></div></div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{publish_down}}')?><div class="input-group-addon"></div>#publish_down#</div>
<div class="clear"></div></div>
</div>
</div>
</div>


<div class="box&#x20;box-full-12&#x20;box-medium-06&#x20;box-large-04">
<div class="widgets-box"><div class="box-header&#x20;box-default"><i class="ion&#x20;ion-clipboard">
</i>
<h3 class="box-title">CONTROLES/ACESSOS
</h3>
</div>
<div class="box-body"><div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{id}}')?>#id#</div>
<div class="clear"></div></div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{codigo}}')?>#codigo#</div>
<div class="clear"></div></div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{state}}')?>#state#</div>
<div class="clear"></div></div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{access}}')?>#access#</div>
<div class="clear"></div></div>
</div>
</div>
</div>

</fildset>