<div class="box&#x20;box-full-12&#x20;box-mini-06&#x20;&#x20;box-small-06&#x20;box-medium-04&#x20;box-large-04&#x20;col-box-list"><div class="widgets-box"><div class="box-header&#x20;box-default"><i class="ion&#x20;ion-android-open"></i><h2 class="box-title">{{title}}</h2><br /><small class="fl-left">CRIADO EM: {{created}}</small><small class="fl-right"> POR: {{editorBy}}</small></div><div class="box-body"><p class="box-description"><div class="box-list">empresa: {{empresa}}</div>
<div class="box-list">said_real: {{said_real}}</div>
<div class="box-list">said_previsto: {{said_previsto}}</div>
<div class="box-list">ent_real: {{ent_real}}</div>
<div class="box-list">ent_previsto: {{ent_previsto}}</div>
<div class="box-list">description: {{description}}</div>
<div class="box-list">ordering: {{ordering}}</div>
<div class="box-list">state: {{state}}</div>
<div class="box-list">created_by: {{created_by}}</div>
<div class="box-list">modified_by: {{modified_by}}</div>
<div class="box-list">alias: {{alias}}</div>
<div class="box-list">modified: {{modified}}</div>
<div class="box-list">publish_up: {{publish_up}}</div>
<div class="box-list">publish_down: {{publish_down}}</div></p></div><div class="box-footer">{{buttons}}</div></div></div>