<div class="box&#x20;box-full-12&#x20;box-mini-06&#x20;&#x20;box-small-06&#x20;box-medium-04&#x20;box-large-04&#x20;col-box-list"><div class="widgets-box"><div class="box-header&#x20;box-default"><i class="ion&#x20;ion-android-open"></i><h2 class="box-title">{{title}}</h2><br /><small class="fl-left">CRIADO EM: {{created}}</small><small class="fl-right"> POR: {{editorBy}}</small></div><div class="box-body"><p class="box-description"><div class="box-list">empresa: {{empresa}}</div>
<div class="box-list">caixa_id: {{caixa_id}}</div>
<div class="box-list">situacao: {{situacao}}</div>
<div class="box-list">repete: {{repete}}</div>
<div class="box-list">perildo: {{perildo}}</div>
<div class="box-list">qtdade: {{qtdade}}</div>
<div class="box-list">conta_id: {{conta_id}}</div>
<div class="box-list">plano_conta_id: {{plano_conta_id}}</div>
<div class="box-list">centro_custo_id: {{centro_custo_id}}</div>
<div class="box-list">fornecedor_id: {{fornecedor_id}}</div>
<div class="box-list">fpgto_id: {{fpgto_id}}</div>
<div class="box-list">tipo_custo: {{tipo_custo}}</div>
<div class="box-list">apropriacao_custo: {{apropriacao_custo}}</div>
<div class="box-list">tipo_documento: {{tipo_documento}}</div>
<div class="box-list">num_documento: {{num_documento}}</div>
<div class="box-list">description: {{description}}</div>
<div class="box-list">ordering: {{ordering}}</div>
<div class="box-list">state: {{state}}</div>
<div class="box-list">created_by: {{created_by}}</div>
<div class="box-list">modified_by: {{modified_by}}</div>
<div class="box-list">alias: {{alias}}</div>
<div class="box-list">modified: {{modified}}</div>
<div class="box-list">publish_up: {{publish_up}}</div>
<div class="box-list">publish_down: {{publish_down}}</div></p></div><div class="box-footer">{{buttons}}</div></div></div>