<div class="box&#x20;box-full-12&#x20;&#x20;box-mini-06&#x20;box-small-06&#x20;box-medium-04&#x20;box-large-&lt;&#x3F;&#x3D;&#x24;qtd_col&#x3F;&gt;&#x20;col-box-list"><div class="widgets-box"><div class="box-header&#x20;box-default"><i class="ion&#x20;ion-android-open"></i><h3 class="box-title">{{title}}</h3><br /><small class="fl-left"><?php echo $this->translate('CRIADO EM: ');?>{{created}}</small><small class="fl-right"><?php echo $this->translate(' POR: ');?>{{editorBy}}</small></div><div class="box-body"><p class="box-description"><div class="box-list&#x20;list-empresa"><i class="ico&#x20;ico-empresa"></i><?php echo $this->translate('empresa');?> {{empresa}}</div>
<div class="box-list&#x20;list-representante"><i class="ico&#x20;ico-representante"></i><?php echo $this->translate('representante');?> {{representante}}</div>
<div class="box-list&#x20;list-phone"><i class="ico&#x20;ico-phone"></i><?php echo $this->translate('phone');?> {{phone}}</div>
<div class="box-list&#x20;list-whatsapp"><i class="ico&#x20;ico-whatsapp"></i><?php echo $this->translate('whatsapp');?> {{whatsapp}}</div>
<div class="box-list&#x20;list-email"><i class="ico&#x20;ico-email"></i><?php echo $this->translate('email');?> {{email}}</div>
<div class="box-list&#x20;list-facebook"><i class="ico&#x20;ico-facebook"></i><?php echo $this->translate('facebook');?> {{facebook}}</div>
<div class="box-list&#x20;list-twitter"><i class="ico&#x20;ico-twitter"></i><?php echo $this->translate('twitter');?> {{twitter}}</div>
<div class="box-list&#x20;list-site"><i class="ico&#x20;ico-site"></i><?php echo $this->translate('site');?> {{site}}</div>
<div class="box-list&#x20;list-cnpj"><i class="ico&#x20;ico-cnpj"></i><?php echo $this->translate('cnpj');?> {{cnpj}}</div>
<div class="box-list&#x20;list-ie"><i class="ico&#x20;ico-ie"></i><?php echo $this->translate('ie');?> {{ie}}</div>
<div class="box-list&#x20;list-cidade"><i class="ico&#x20;ico-cidade"></i><?php echo $this->translate('cidade');?> {{cidade}}</div>
<div class="box-list&#x20;list-bairro"><i class="ico&#x20;ico-bairro"></i><?php echo $this->translate('bairro');?> {{bairro}}</div>
<div class="box-list&#x20;list-endereco"><i class="ico&#x20;ico-endereco"></i><?php echo $this->translate('endereco');?> {{endereco}}</div>
<div class="box-list&#x20;list-images"><i class="ico&#x20;ico-images"></i><?php echo $this->translate('images');?> {{images}}</div>
<div class="box-list&#x20;list-description"><i class="ico&#x20;ico-description"></i><?php echo $this->translate('description');?> {{description}}</div>
<div class="box-list&#x20;list-ordering"><i class="ico&#x20;ico-ordering"></i><?php echo $this->translate('ordering');?> {{ordering}}</div>
<div class="box-list&#x20;list-state"><i class="ico&#x20;ico-state"></i><?php echo $this->translate('state');?> {{state}}</div>
<div class="box-list&#x20;list-created_by"><i class="ico&#x20;ico-created_by"></i><?php echo $this->translate('created_by');?> {{created_by}}</div>
<div class="box-list&#x20;list-modified_by"><i class="ico&#x20;ico-modified_by"></i><?php echo $this->translate('modified_by');?> {{modified_by}}</div>
<div class="box-list&#x20;list-alias"><i class="ico&#x20;ico-alias"></i><?php echo $this->translate('alias');?> {{alias}}</div>
<div class="box-list&#x20;list-modified"><i class="ico&#x20;ico-modified"></i><?php echo $this->translate('modified');?> {{modified}}</div>
<div class="box-list&#x20;list-publish_up"><i class="ico&#x20;ico-publish_up"></i><?php echo $this->translate('publish_up');?> {{publish_up}}</div>
<div class="box-list&#x20;list-publish_down"><i class="ico&#x20;ico-publish_down"></i><?php echo $this->translate('publish_down');?> {{publish_down}}</div></p></div><div class="box-footer">{{buttons}}</div></div></div>