<fildset><legend>FORMULARIO DE MANUTENÇÃO</legend><div class="box&#x20;box-full-12&#x20;box-medium-06&#x20;box-large-08"><div class="widgets-box"><div class="box-header&#x20;box-default"><i class="ion&#x20;ion-clipboard"></i><h3 class="box-title">GERAL</h3></div><div class="box-body"><div class="form-group">{{title}}#title#</div>
<div class="form-group">{{description}}#description#</div>
<div class="form-group">{{alias}}#alias#</div>
<div class="form-group">{{icone}}#icone#</div>
#asset_id##empresa##created_by##modified_by##ordering##modified##security#</div>
            <div class="box-footer"><div class="pull-right">#save##save_copy#<a class="btn btn-black" href="/operacional/bs-grupos/index">BTN_VOLTAR_LABEL</a><p></div></div></div></div>
            <div class="box&#x20;box-full-12&#x20;box-medium-06&#x20;box-large-04">
                <div class="widgets-box"><div class="box-header&#x20;box-default"><i class="ion&#x20;ion-clipboard"></i><h3 class="box-title">CONTROLES</h3></div><div class="box-body"><div class="form-group">{{id}}#id#</div>
<div class="form-group">{{codigo}}#codigo#</div>
<div class="form-group">{{state}}#state#</div>
<div class="form-group">{{access}}#access#</div></div></div></div><div class="box&#x20;box-full-12&#x20;box-medium-06&#x20;box-large-04"><div class="widgets-box"><div class="box-header&#x20;box-default"><i class="ion&#x20;ion-clipboard"></i><h3 class="box-title">DATAS</h3></div><div class="box-body"><div class="form-group">{{created}}<div class="input-group-addon"></div>#created#</div>
<div class="form-group">{{publish_up}}<div class="input-group-addon"></div>#publish_up#</div>
<div class="form-group">{{publish_down}}<div class="input-group-addon"></div>#publish_down#</div></div></div></div></fildset>