<fildset><legend>FORMULARIO DE MANUTENÇÃO</legend><div class="box&#x20;box-full-12&#x20;box-medium-06&#x20;box-large-08"><div class="widgets-box"><div class="box-header&#x20;box-default"><i class="ion&#x20;ion-clipboard">
</i>
<h3 class="box-title">GERAL
</h3>
</div>
<div class="box-body"><div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{title}}')?>#title#</div>
<div class="clear"></div></div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{subtitle}}')?>#subtitle#</div>
<div class="clear"></div></div>

<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-05&#x20;box-large-04"><?php echo $this->translate('{{tipo}}')?>#tipo#</div>

<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-07&#x20;box-large-08"><?php echo $this->translate('{{barra}}')?>#barra#</div>
<div class="clear"></div></div>

<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-06&#x20;box-large-06"><?php echo $this->translate('{{cat_id}}')?>#cat_id#</div>

<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-06&#x20;box-large-06"><?php echo $this->translate('{{marca_id}}')?>#marca_id#</div>
<div class="clear"></div></div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-04&#x20;box-large-04"><?php echo $this->translate('{{clfiscal}}')?>#clfiscal#</div>

<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-02&#x20;box-large-02"><?php echo $this->translate('{{ecfop}}')?>#ecfop#</div>

<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-02&#x20;box-large-02"><?php echo $this->translate('{{scfop}}')?>#scfop#</div>

<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-02&#x20;box-large-02"><?php echo $this->translate('{{cst}}')?>#cst#</div>

<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-02&#x20;box-large-02"><?php echo $this->translate('{{unidade_trib}}')?>#unidade_trib#</div>
<div class="clear"></div></div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-04&#x20;box-large-04"><?php echo $this->translate('{{pago}}')?>#pago#</div>
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-04&#x20;box-large-04"><?php echo $this->translate('{{marge_lucro}}')?>#marge_lucro#</div>
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-04&#x20;box-large-04"><?php echo $this->translate('{{valor}}')?>#valor#</div>
<div class="clear"></div></div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-02&#x20;box-large-02"><?php echo $this->translate('{{estoque}}')?>#estoque#</div>
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-02&#x20;box-large-02"><?php echo $this->translate('{{estoque_minimo}}')?>#estoque_minimo#</div>
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-02&#x20;box-large-02"><?php echo $this->translate('{{dim_width}}')?>#dim_width#</div>
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-02&#x20;box-large-02"><?php echo $this->translate('{{dim_heigth}}')?>#dim_heigth#</div>
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-02&#x20;box-large-02"><?php echo $this->translate('{{dim_depth}}')?>#dim_depth#</div>
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-02&#x20;box-large-02"><?php echo $this->translate('{{dim_weight}}')?>#dim_weight#</div>
<div class="clear"></div></div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{description}}')?>#description#</div>
<div class="clear"></div></div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{alias}}')?>#alias#</div>
<div class="clear"></div></div>
#asset_id##empresa##created_by##modified_by##ordering##modified##security#
</div>
<div class="box-footer"><div class="pull-right">#save##save_copy#<a class="btn btn-black" href="/admin/bs-produtos/index"><?php echo $this->translate('BTN_VOLTAR_LABEL');?></a><p>
</div>
</div>

</div>
</div>
<!-- ################################# FIM GERAL ################################# -->
<div class="box&#x20;box-full-12&#x20;box-medium-06&#x20;box-large-04"><div class="widgets-box"><div class="box-header&#x20;box-default"><i class="ion&#x20;ion-clipboard">
</i>
<h3 class="box-title">CONTROLES
</h3>
</div>
<div class="box-body"><div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{id}}');?>#id#</div>
<div class="clear"></div></div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{codigo}}');?>#codigo#</div>
<div class="clear"></div></div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{state}}');?>#state#</div>
<div class="clear"></div></div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{access}}');?>#access#</div>
<div class="clear"></div></div>
</div>


</div>
</div>
<!--################################# FIM CONTROLE ################################# -->
<div class="box&#x20;box-full-12&#x20;box-medium-06&#x20;box-large-04"><div class="widgets-box"><div class="box-header&#x20;box-default"><i class="ion&#x20;ion-clipboard">
</i>
<h3 class="box-title">IMAGENS
</h3>
</div>
<div class="box-body"><div class="img-add&#x20;"><?php echo $this->translate('{{images}}');?>#imagePreview#</div>
<div class="row">
<div class="input-group&#x20;class-file"><div class="btn&#x20;btn-blue&#x20;btn-file"><i class="ion&#x20;ion-android-upload"></i><span class="file-text">Selecione uma imagem</span>
<input name="attachment" type="file" id="attachment" />#images#
</div><p class="help-block">Max. 32MB</p></div>
</div>
</div>


</div>
</div>
<!-- ################################# FIM IMAGES ###########################-->
<div class="box&#x20;box-full-12&#x20;box-medium-06&#x20;box-large-04"><div class="widgets-box"><div class="box-header&#x20;box-default"><i class="ion&#x20;ion-clipboard">
</i>
<h3 class="box-title">DATAS
</h3>
</div>
<div class="box-body"><div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{created}}');?><div class="input-group-addon"></div>#created#</div>
<div class="clear"></div></div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{publish_up}}');?><div class="input-group-addon"></div>#publish_up#</div>
<div class="clear"></div></div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{publish_down}}');?><div class="input-group-addon"></div>#publish_down#</div>
<div class="clear"></div></div>
</div>


</div>
</div>
<!-- ################################## FIM DATAS ###################### -->
</fildset>