<fildset><legend>FORMULARIO DE MANUTENÇÃO</legend><div class="box&#x20;box-full-12&#x20;box-medium-06&#x20;box-large-08"><div class="widgets-box"><div class="box-header&#x20;box-default"><i class="ion&#x20;ion-clipboard"></i><h3 class="box-title">GERAL</h3></div><div class="box-body"><div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12">{{title}}#title#</div>
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12">{{description}}#description#</div>
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12">{{template}}#template#</div>
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12">{{group_id}}#group_id#</div>
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12">{{tipo_modulo}}#tipo_modulo#</div>
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12">{{route}}#route#</div>
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12">{{controller}}#controller#</div>
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12">{{action_default}}#action_default#</div>
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12">{{arquivo}}#arquivo#</div>
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12">{{tabela}}#tabela#</div>
#asset_id##empresa##created_by##modified_by##ordering##modified##security#</div><div class="box-footer"><div class="pull-right">#save##save_copy#<a class="btn btn-black" href="/operacional/bs-resources/index">BTN_VOLTAR_LABEL</a><p></div></div></div></div><div class="box&#x20;box-full-12&#x20;box-medium-06&#x20;box-large-04"><div class="widgets-box"><div class="box-header&#x20;box-default"><i class="ion&#x20;ion-clipboard"></i><h3 class="box-title">CONTROLES</h3></div><div class="box-body"><div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12">{{id}}#id#</div>
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12">{{codigo}}#codigo#</div>
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12">{{alias}}#alias#</div>
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12">{{state}}#state#</div>
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12">{{access}}#access#</div>
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12">{{module_id}}#module_id#</div>
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12">{{registro_page}}#registro_page#</div>
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12">{{colunas_linha}}#colunas_linha#</div></div></div></div><div class="box&#x20;box-full-12&#x20;box-medium-06&#x20;box-large-04"><div class="widgets-box"><div class="box-header&#x20;box-default"><i class="ion&#x20;ion-clipboard"></i><h3 class="box-title">DATAS</h3></div><div class="box-body"><div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12">{{created}}<div class="input-group-addon"></div>#created#</div>
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12">{{publish_up}}<div class="input-group-addon"></div>#publish_up#</div>
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12">{{publish_down}}<div class="input-group-addon"></div>#publish_down#</div></div></div></div></fildset>