<?php echo $this->messages(); ?>
<?=
$this->headTitle(strtoupper(substr($this->controller, 3)));
extract($user);
?>

<section class="content-header">
    <h1>
        Bem Vindo <?php echo $title ?>
    </h1>
    <div class="breadcrumb">
        <ul class="breadcrumbs-item">
            <li>Admin</li>
            <li class="divisor"> / </li>
            <li>Panel</li>
            <li class="divisor"> / </li>
            <li><a href="<?php echo $this->url($route, array('controller' => $controller, 'action' => "index")) ?>"><?= ucfirst($controller) ?> </a></li>
        </ul>
     
    </div>
</section>

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="collapse navbar-collapse">
        
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<div id="tabs" class="nav-tabs-custom">
    <ul class="nav nav-tabs">
        <li class=""><a class="tabLink" href="#principal"><?php echo $this->translate('TAB_GERAR_CLASS_LABEL') ?></a></li>
        <li class="pull-right"><i class="ion ion-gear-b"></i></li>
    </ul>
    <div class="tab-content">
        <div id="principal" class="tab-pane ui-state-active">
            <?php 
            $options=[''=>'--Selecione--'];
            foreach ($this->data as $r):
                       $options[$r->getId()]=$r->getTitle();
             endforeach; ?>
            
            <?php
            $actions['']="--Selecione--";
            $actions[$this->url('zen-code/default', array('controller' => 'zen-code', 'action' => 'gerar-module'))]="Gerar Module";
            $actions[$this->url('zen-code/default', array('controller' => 'zen-code', 'action' => 'gerar-module-config'))]="Gerar Module Config";
            $actions[$this->url('zen-code/default', array('controller' => 'zen-code', 'action' => 'gerar-controller'))]="Gerar Controller";
            $actions[$this->url('zen-code/default', array('controller' => 'zen-code', 'action' => 'gerar-model'))]="Gerar Model";
            $actions[$this->url('zen-code/default', array('controller' => 'zen-code', 'action' => 'gerar-model-factory'))]="Gerar Factory Model";
            $actions[$this->url('zen-code/default', array('controller' => 'zen-code', 'action' => 'gerar-table'))]="Gera Table";
            $actions[$this->url('zen-code/default', array('controller' => 'zen-code', 'action' => 'gerar-table-factory'))]="Gera Factory Table";
            $actions[$this->url('zen-code/default', array('controller' => 'zen-code', 'action' => 'gerar-form'))]="Gerar Form";
            $actions[$this->url('zen-code/default', array('controller' => 'zen-code', 'action' => 'gerar-filter'))]="Gerar Filter";
            $actions[$this->url('zen-code/default', array('controller' => 'zen-code', 'action' => 'gerar-form-factory'))]="Gerar Form Factory";
            $actions[$this->url('zen-code/default', array('controller' => 'zen-code', 'action' => 'gerar-view'))]="Gerar View";
            $actions[$this->url('zen-code/default', array('controller' => 'zen-code', 'action' => 'gerar-navigation'))]="Gerar Navegação";
            $actions[$this->url('zen-code/default', array('controller' => 'zen-code', 'action' => 'gerar-tradutor'))]="Gerar Tradução";
            
            $alert =$this->HtmlTag('div')->setClass("trigger trigger_alert")->setText('<b>ATENÇÃO</b>: Ao Restaurar O Arquivo Ou Class Ao Seu Estado Original, Todas As Alterações Feitas Serão Perdidas.');
            $ModelForm[] =$this->HtmlTag('p')->setText($alert);
            $ModelForm[] = $this->FormHelper()->getZenCodeForm('ModelForm', 'update', 'EDITAR MODEL', $options,$actions);
            $box1 = $this->FormHelper()->boxWidgets(array('body' =>implode("<p>",$ModelForm), "title" => "ATUALIZAR MODEL", "class" => "box-default", 'footer' => "", 'icone' => 'clipboard'));
            echo $this->HtmlTag('div')->setClass('box box-full-12')->setText($box1);
            ?>
        </div><!-- /.tab-pane -->

        <div class="clear"></div>
    </div><!-- /.tab-content -->
</div>