<div class="box&#x20;box-full-12&#x20;box-mini-06&#x20;&#x20;box-small-06&#x20;box-medium-04&#x20;box-large-04&#x20;col-box-list">
<div class="widgets-box">
<div class="box-header&#x20;box-default">
<i class="ion&#x20;ion-android-open"></i>
<h2 class="box-title">{{title}}</h2>
<br />
<small class="fl-left">CRIADO EM: {{created}}</small><small class="fl-right"> POR: {{editor_by}}</small>
</div>
<div class="box-body">
    <p class="box-description">
   

     <div class="box-list&#x20;list-ent_previsto"><i class="ico&#x20;ico-ent_previsto"></i><span class="label-list&#x20;label-list-ent_previsto">ent_previsto :</span><span class="data-list&#x20;data-list-ent_previsto">{{ent_previsto}}</span>
    </div>

     <div class="box-list&#x20;list-ent_real"><i class="ico&#x20;ico-ent_real"></i><span class="label-list&#x20;label-list-ent_real">ent_real :</span><span class="data-list&#x20;data-list-ent_real">{{ent_real}}</span>
    </div>

     <div class="box-list&#x20;list-said_previsto"><i class="ico&#x20;ico-said_previsto"></i><span class="label-list&#x20;label-list-said_previsto">said_previsto :</span><span class="data-list&#x20;data-list-said_previsto">{{said_previsto}}</span>
    </div>

     <div class="box-list&#x20;list-said_real"><i class="ico&#x20;ico-said_real"></i><span class="label-list&#x20;label-list-said_real">said_real :</span><span class="data-list&#x20;data-list-said_real">{{said_real}}</span>
    </div>
   
     
    <div class="box-list&#x20;list-alias"><i class="ico&#x20;ico-alias"></i><span class="label-list&#x20;label-list-alias">alias :</span><span class="data-list&#x20;data-list-alias">{{alias}}</span>
    </div>
     <div class="box-list&#x20;list-description"><i class="ico&#x20;ico-description"></i><span class="label-list&#x20;label-list-description">description :</span><span class="data-list&#x20;data-list-description">{{description}}</span></div>

        <div class="box-list&#x20;list-state">
        <i class="ico&#x20;ico-state"></i><span class="label-list&#x20;label-list-state">state :</span>
        <span class="data-list&#x20;data-list-state">{{state}}</span></div>
   
    <div class="box-list&#x20;list-publish_up"><i class="ico&#x20;ico-publish_up"></i><span class="label-list&#x20;label-list-publish_up">publish_up :</span><span class="data-list&#x20;data-list-publish_up">{{publish_up}}</span>
    </div>
    <div class="box-list&#x20;list-publish_down"><i class="ico&#x20;ico-publish_down"></i><span class="label-list&#x20;label-list-publish_down">publish_down :</span><span class="data-list&#x20;data-list-publish_down">{{publish_down}}</span></div>
     </p>
    </div>
<div class="box-footer">{{buttons}}</div>
</div>
</div>