<div class="box&#x20;box-full-12&#x20;box-mini-06&#x20;&#x20;box-small-06&#x20;box-medium-04&#x20;box-large-04&#x20;col-box-list">
<div class="widgets-box">
<div class="box-header&#x20;box-default">
<i class="ion&#x20;ion-android-open"></i>
<h2 class="box-title">{{title}}</h2>
<br />
<small class="fl-left"><?php echo $this->translate('CRIADO EM: ');?>{{created}}</small><small class="fl-right"><?php echo $this->translate(' POR: ');?>{{editor_by}}</small>
</div>
<div class="box-body">
<p class="box-description">

<div class="box-list&#x20;list-caixa_id">
<i class="ico&#x20;ico-caixa_id"></i>
<span class="label-list&#x20;label-list-caixa_id">
<?php echo $this->translate('Caixa');?> :
</span>
<span class="data-list&#x20;data-list-caixa_id">{{caixa_title}}</span>
</div>
<div class="box-list&#x20;list-situacao">
<i class="ico&#x20;ico-situacao"></i>
<span class="label-list&#x20;label-list-situacao">
<?php echo $this->translate('Situação');?> :
</span>
<span class="data-list&#x20;data-list-situacao">{{title_bs_conta_situacao}}</span>
</div>
<div class="box-list&#x20;list-repete">
<i class="ico&#x20;ico-repete"></i>
<span class="label-list&#x20;label-list-repete">
<?php echo $this->translate('Repéte');?> :
</span>
<span class="data-list&#x20;data-list-repete">{{title_bs_conta_repete}}</span>
</div>
<div class="box-list&#x20;list-periodos">
<i class="ico&#x20;ico-periodos"></i>
<span class="label-list&#x20;label-list-periodos">
<?php echo $this->translate('periodos');?> :
</span>
<span class="data-list&#x20;data-list-periodos">{{title_bs_conta_periodos}}</span>
</div>
<div class="box-list&#x20;list-qtdade">
<i class="ico&#x20;ico-qtdade"></i>
<span class="label-list&#x20;label-list-qtdade">
<?php echo $this->translate('qtdade');?> :
</span>
<span class="data-list&#x20;data-list-qtdade">{{qtdade}}</span>
</div>
<div class="box-list&#x20;list-conta_id">
<i class="ico&#x20;ico-conta_id"></i>
<span class="label-list&#x20;label-list-conta_id">
<?php echo $this->translate('Tipo/Conta');?> :
</span>
<span class="data-list&#x20;data-list-conta_id">{{title_bs_contas}}</span>
</div>
<div class="box-list&#x20;list-valor">
<i class="ico&#x20;ico-valor"></i>
<span class="label-list&#x20;label-list-valor">
<?php echo $this->translate('valor');?> :
</span>
<span class="data-list&#x20;data-list-valor">{{valor}}</span>
</div>
<div class="box-list&#x20;list-plano_conta_id">
<i class="ico&#x20;ico-plano_conta_id"></i>
<span class="label-list&#x20;label-list-plano_conta_id">
<?php echo $this->translate('Plano/Conta');?> :
</span>
<span class="data-list&#x20;data-list-plano_conta_id">{{title_bs_planos_contas}}</span>
</div>
<div class="box-list&#x20;list-centro_custo_id">
<i class="ico&#x20;ico-centro_custo_id"></i>
<span class="label-list&#x20;label-list-centro_custo_id">
<?php echo $this->translate('centro_custo_id');?> :
</span>
<span class="data-list&#x20;data-list-centro_custo_id">{{centro_custo_id}}</span>
</div>
<div class="box-list&#x20;list-fornecedor_id">
<i class="ico&#x20;ico-fornecedor_id"></i>
<span class="label-list&#x20;label-list-fornecedor_id">
<?php echo $this->translate('Fornecedor');?> :
</span>
<span class="data-list&#x20;data-list-fornecedor_id">{{title_bs_fornecedor}}</span>
</div>
<div class="box-list&#x20;list-fpgto_id">
<i class="ico&#x20;ico-fpgto_id"></i>
<span class="label-list&#x20;label-list-fpgto_id">
<?php echo $this->translate('fpgto_id');?> :
</span>
<span class="data-list&#x20;data-list-fpgto_id">{{fpgto_id}}</span>
</div>
<div class="box-list&#x20;list-tipo_custo">
<i class="ico&#x20;ico-tipo_custo"></i>
<span class="label-list&#x20;label-list-tipo_custo">
<?php echo $this->translate('Tipo/Custo');?> :
</span>
<span class="data-list&#x20;data-list-tipo_custo">{{title_bs_tipo_custo}}</span>
</div>
<div class="box-list&#x20;list-apropriacao_custo">
<i class="ico&#x20;ico-apropriacao_custo"></i>
<span class="label-list&#x20;label-list-apropriacao_custo">
<?php echo $this->translate('Apropriacao/Custo');?> :
</span>
<span class="data-list&#x20;data-list-apropriacao_custo">{{title_bs_apropriacao_custo}}</span>
</div>
<div class="box-list&#x20;list-tipo_documento">
<i class="ico&#x20;ico-tipo_documento"></i>
<span class="label-list&#x20;label-list-tipo_documento">
<?php echo $this->translate('Tipo/Documento');?> :
</span>
<span class="data-list&#x20;data-list-tipo_documento">{{title_bs_tipo_documento}}</span>
</div>
<div class="box-list&#x20;list-num_documento">
<i class="ico&#x20;ico-num_documento"></i>
<span class="label-list&#x20;label-list-num_documento">
<?php echo $this->translate('num_documento');?> :
</span>
<span class="data-list&#x20;data-list-num_documento">{{num_documento}}</span>
</div>
<div class="box-list&#x20;list-description">
<i class="ico&#x20;ico-description"></i>
<span class="label-list&#x20;label-list-description">
<?php echo $this->translate('description');?> :
</span>
<span class="data-list&#x20;data-list-description">{{description}}</span>
</div>

<div class="box-list&#x20;list-state">
<i class="ico&#x20;ico-state"></i>
<span class="label-list&#x20;label-list-state">
<?php echo $this->translate('state');?> :
</span>
<span class="data-list&#x20;data-list-state">{{state}}</span>
</div>

<div class="box-list&#x20;list-alias">
<i class="ico&#x20;ico-alias"></i>
<span class="label-list&#x20;label-list-alias">
<?php echo $this->translate('alias');?> :
</span>
<span class="data-list&#x20;data-list-alias">{{alias}}</span>
</div>
<div class="box-list&#x20;list-modified">
<i class="ico&#x20;ico-modified"></i>
<span class="label-list&#x20;label-list-modified">
<?php echo $this->translate('modified');?> :
</span>
<span class="data-list&#x20;data-list-modified">{{modified}}</span>
</div>
<div class="box-list&#x20;list-publish_up">
<i class="ico&#x20;ico-publish_up"></i>
<span class="label-list&#x20;label-list-publish_up">
<?php echo $this->translate('publish_up');?> :
</span>
<span class="data-list&#x20;data-list-publish_up">{{publish_up}}</span>
</div>
<div class="box-list&#x20;list-publish_down">
<i class="ico&#x20;ico-publish_down"></i>
<span class="label-list&#x20;label-list-publish_down">
<?php echo $this->translate('publish_down');?> :
</span>
<span class="data-list&#x20;data-list-publish_down">{{publish_down}}</span>
</div></p></div>
<div class="box-footer">{{buttons}}</div>
</div>
</div>