<h1>Please fill the form and hit the button.</h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('auth/default', array('controller' => 'registration', 'action' => 'forgotten-password')));
$form->prepare();
$form->setAttribute('class', 'form-inline');
$this->formElementErrors()
        ->setMessageOpenFormat('<ul class="nav"><li class="erro-obrigatorio">')
        ->setMessageSeparatorString('</li>')->render($form);
echo $this->form()->openTag($form);
echo $this->formRow($form->get('email'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
