<style>
    .login-box{margin: 60px auto;float: left;width: 100%;}
    .main-login-header{text-align: left;display: block;width: 500px;max-width: 90%;margin: 0 auto;background: #fff;padding: 0;}
    .login-box-body{text-align: left;display: block;width: 500px;max-width: 90%;margin:0 auto 25px auto;background: #fff;padding: 25px;box-shadow: 0 0 5px 0 #ccc;}
    .form-group{margin: 15px 0;}
    .login-logo{padding-bottom: 0;}
    .login-box a{color: #555;text-decoration: none;font-size: 0.8em;margin-top: 10px;text-transform: uppercase;font-weight: 300;padding-top: 20px;}
    .login-box a:hover{text-decoration: underline;}
</style>
<div class="box login-box">
    <div class="main-login-header">
        <a href="<?php echo $this->url('home') ?>"><img src="/admin_assets/img/logo-siga-q.png"></a>
    </div><!-- /.login-logo -->
    <div class="main-login-box login-box-body">
        <p class="trigger trigger_info">Informeu seu e-mail abaixo. Você receberá uma link para recuperar sua senha!</p>
        <?php echo $this->messages(); ?>
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('auth/default', array('controller' => 'registration', 'action' => 'forgotten-password')));
        $form->prepare();
        $this->formElementErrors()
                ->setMessageOpenFormat('<ul class="nav"><li class="erro-obrigatorio">')
                ->setMessageSeparatorString('</li>')->render($form);
        echo $this->form()->openTag($form);
        ?>
        <div class="form-group has-feedback">
            <?php echo $this->formEmail($form->get('email')); ?>
            <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <?php echo $this->formSubmit($form->get('submit')); ?>
            </div><!-- /.col -->
        </div>
        <?php echo $this->form()->closeTag(); ?>

        <p>
            <a  href="<?php echo $this->url('auth') ?>">&larrhk; Voltar para Tela de Login!</a><br>

    </div><!-- /.login-box-body -->
</div><!-- /.login-box -->
