<h1>Registration</h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('auth/default', array('controller' => 'registration', 'action' => 'index')));

$form->setAttribute('class', 'form-inline');
$this->formElementErrors()
        ->setMessageOpenFormat('<ul class="nav"><li class="erro-obrigatorio">')
        ->setMessageSeparatorString('</li>')->render($form);
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
