<fildset>
<legend>FORMULARIO DE MANUTENÇÃO</legend>
<div class="box&#x20;box-full-12&#x20;box-medium-06&#x20;box-large-08">
<div class="widgets-box">
<div class="box-header&#x20;box-default">
<i class="ion&#x20;ion-clipboard"></i>
<h3 class="box-title">GERAL</h3>
</div>
<div class="box-body">
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{title}}');?>#title#</div>
<div class="clear"></div>
</div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{description}}');?>#description#</div>
<div class="clear"></div>
</div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{alias}}');?>#alias#</div>
<div class="clear"></div>
</div>
#asset_id##empresa##created_by##modified_by##ordering##modified##security#</div>
<div class="box-footer">
<div class="pull-right">
#save##save_copy#<a class="btn btn-black" href="/fluxo-caixa/bs-conta-periodos/index">VOLTAR</a><p>
</div>
</div>
</div>
</div>
<div class="box&#x20;box-full-12&#x20;box-medium-06&#x20;box-large-04">
<div class="widgets-box">
<div class="box-header&#x20;box-default">
<i class="ion&#x20;ion-clipboard"></i>
<h3 class="box-title">CONTROLES</h3>
</div>
<div class="box-body">
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{id}}');?>#id#</div>
<div class="clear"></div>
</div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{codigo}}');?>#codigo#</div>
<div class="clear"></div>
</div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{state}}');?>#state#</div>
<div class="clear"></div>
</div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{access}}');?>#access#</div>
<div class="clear"></div>
</div></div>

</div>
</div>
<div class="box&#x20;box-full-12&#x20;box-medium-06&#x20;box-large-04">
<div class="widgets-box">
<div class="box-header&#x20;box-default">
<i class="ion&#x20;ion-clipboard"></i>
<h3 class="box-title">DATAS</h3>
</div>
<div class="box-body">
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{created}}');?><div class="input-group-addon"></div>#created#</div>
<div class="clear"></div>
</div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{publish_up}}');?><div class="input-group-addon"></div>#publish_up#</div>
<div class="clear"></div>
</div>
<div class="row">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12"><?php echo $this->translate('{{publish_down}}');?><div class="input-group-addon"></div>#publish_down#</div>
<div class="clear"></div>
</div></div>

</div>
</div>
</fildset>