<?php extract($data); ?>
<form action="<?php echo $this->url($this->route,array('controller'=>$this->controller,'action'=>'inserir')) ?>" class="form-horizontal" method="post">
<div class="row">
	<div class="col-md-6">
		

  	<legend>Form Edição</legend>
  <div class="form-group">
  		<label for="Id">Id</label>
  		<input type="text" class="form-control" id="id" name="id"  value="<?php echo $id ?>" placeholder="Codigo">
  	</div>
 
  	<div class="form-group">
  		<label for="">Codigo</label>
  		<input type="text" class="form-control" id="codigo" name="codigo"  value="<?php echo $codigo ?>" placeholder="Codigo">
  	</div>
  
  	<div class="form-group">
  		<label for="">AssetId</label>
  		<input type="text" class="form-control" id="asset_id" name="asset_id" value="<?php echo $asset_id ?>" placeholder="Asset_id">
  	</div>

  	<div class="form-group">
  		<label for="Empresa">Empresa</label>
  		<input type="text" class="form-control" id="empresa" name="empresa" value="<?php echo $empresa ?>" placeholder="Asset_id">
  	</div>

  	<div class="form-group">
  		<label for="title">Title</label>
  		<input type="text" class="form-control" id="title" name="title" value="<?php echo $title ?>" placeholder="Asset_id">
  	</div>

  	 <div class="form-group">
  		<label for="images">images</label>
  		<input type="text" class="form-control" id="images" name="images" value="<?php echo $images ?>"  placeholder="images">
  	</div>
  	 
     <div class="form-group">
  		<label for="description">description</label>
  		<textarea class="form-control" id="description" name="description"><?php echo $description ?></textarea>
  	</div>

  	 <div class="form-group">
  		<label for="created_by">created_by</label>
  		<input type="text" class="form-control" id="created_by" name="created_by"  value="<?php echo $created_by ?>" placeholder="created_by">
  	</div>

  	<div class="form-group">
  		<label for="modified_by">modified_by</label>
  		<input type="text" class="form-control" id="modified_by" name="modified_by"  value="<?php echo $modified_by ?>" placeholder="modified_by">
  	</div>

  	 <div class="form-group">
  		<label for="alias">alias</label>
  		<input type="text" class="form-control" id="alias" name="alias" value="<?php echo $alias ?>" placeholder="alias">
  	</div>

      </div>
    <div class="col-md-6">

  	 <div class="form-group">
  		<label for="ordering">ordering</label>
  		<input type="text" class="form-control" id="ordering" name="ordering" value="<?php echo $ordering ?>" placeholder="ordering">
  	</div>

  	 <div class="form-group">
  		<label for="state">state</label>
  		<input type="text" class="form-control" id="state" name="state" value="<?php echo $state ?>" placeholder="state">
  	</div>
  	 <div class="form-group">
  		<label for="access">access</label>
  		<input type="text" class="form-control" id="access" name="access" value="<?php echo $access ?>" placeholder="access">
  	</div>

  	 <div class="form-group">
  		<label for="created">created</label>
  		<input type="text" class="form-control" id="created" value="<?php echo date('d-m-Y') ?>" name="created" placeholder="created">
  	</div>

  	 <div class="form-group">
  		<label for="modified">modified</label>
  		<input type="text" class="form-control" id="modified" name="modified" value="<?php echo date('d-m-Y') ?>" placeholder="modified">
  	</div>
  	 <div class="form-group">
  		<label for="publish_up">publish_up</label>
  		<input type="text" class="form-control" id="publish_up" value="<?php echo date('d-m-Y') ?>" name="publish_up" placeholder="publish_up">
  	</div>
  	 <div class="form-group">
  		<label for="publish_down">publish_down</label>
  		<input type="text" class="form-control" id="publish_down" value="<?php echo date('d-m-Y') ?>" name="publish_down" placeholder="publish_down">
  	</div>

  	<button type="submit" class="btn btn-primary">Atualizar</button>
  

	</div>
</div>
</form>