<form action="<?php echo $this->url($this->route,array('controller'=>$this->controller,'action'=>'inserir')) ?>" class="form-horizontal" method="post">
<div class="row">
	<div class="col-md-6">
		

  	<legend>Form title</legend>
  
 
  	<div class="form-group">
  		<label for="">Codigo</label>
  		<input type="text" class="form-control" id="codigo" name="codigo"  value="5" placeholder="Codigo">
  	</div>
  
  	<div class="form-group">
  		<label for="">AssetId</label>
  		<input type="text" class="form-control" id="asset_id" name="asset_id" value="1" placeholder="Asset_id">
  	</div>

  	<div class="form-group">
  		<label for="Empresa">Empresa</label>
  		<input type="text" class="form-control" id="empresa" name="empresa" value="1" placeholder="Asset_id">
  	</div>

  	<div class="form-group">
  		<label for="title">Title</label>
  		<input type="text" class="form-control" id="title" name="title" value="claudio" placeholder="Asset_id">
  	</div>

  	<div class="form-group">
  		<label for="Email">Email</label>
  		<input type="text" class="form-control" id="Email" name="Email" value="cal.tj@hotmail.com" placeholder="Email">
  	</div>
  
   <div class="form-group">
  		<label for="facebook">facebook</label>
  		<input type="text" class="form-control" id="facebook" name="facebook" placeholder="facebook">
  	</div>

  	 <div class="form-group">
  		<label for="twitter">twitter</label>
  		<input type="text" class="form-control" id="twitter" name="twitter" placeholder="twitter">
  	</div>

  	 <div class="form-group">
  		<label for="phone">phone</label>
  		<input type="text" class="form-control" id="phone" name="phone" value="96535664" placeholder="phone">
  	</div>
  	
  	 <div class="form-group">
  		<label for="endereco">endereco</label>
  		<input type="text" class="form-control" id="endereco" name="endereco"  value="Rua jose juist" placeholder="endereco">
  	</div>

  	 <div class="form-group">
  		<label for="bairro">bairro</label>
  		<input type="text" class="form-control" id="bairro" name="bairro"  value="centro" placeholder="bairro">
  	</div>

  	 <div class="form-group">
  		<label for="cidade">cidade</label>
  		<input type="text" class="form-control" id="cidade" name="cidade"  value="jacinto machado" placeholder="cidade">
  	</div>

  	 <div class="form-group">
  		<label for="images">images</label>
  		<input type="text" class="form-control" id="images" name="images"  placeholder="images">
  	</div>
  	 <div class="form-group">
  		<label for="password">password</label>
  		<input type="text" class="form-control" id="password" name="password" placeholder="password">
  	</div>
  	</div>
  	<div class="col-md-6">
  	 <div class="form-group">
  		<label for="role_id">role_id</label>
  		<input type="text" class="form-control" id="role_id" name="role_id"  value="3" placeholder="role_id">
  	</div>

  	 <div class="form-group">
  		<label for="description">description</label>
  		<input type="text" class="form-control" id="description" name="description" placeholder="description">
  	</div>

  	 <div class="form-group">
  		<label for="created_by">created_by</label>
  		<input type="text" class="form-control" id="created_by" name="created_by"  value="1" placeholder="created_by">
  	</div>

  	<div class="form-group">
  		<label for="modified_by">modified_by</label>
  		<input type="text" class="form-control" id="modified_by" name="modified_by"  value="1" placeholder="modified_by">
  	</div>

  	 <div class="form-group">
  		<label for="alias">alias</label>
  		<input type="text" class="form-control" id="alias" name="alias" value="Usuario Admin" placeholder="alias">
  	</div>

  	 <div class="form-group">
  		<label for="ordering">ordering</label>
  		<input type="text" class="form-control" id="ordering" name="ordering" value="1" placeholder="ordering">
  	</div>

  	 <div class="form-group">
  		<label for="state">state</label>
  		<input type="text" class="form-control" id="state" name="state" value="1" placeholder="state">
  	</div>
  	 <div class="form-group">
  		<label for="access">access</label>
  		<input type="text" class="form-control" id="access" name="access" value="1" placeholder="access">
  	</div>

  	 <div class="form-group">
  		<label for="created">created</label>
  		<input type="text" class="form-control" id="created" value="<?php echo date('d-m-Y') ?>" name="created" placeholder="created">
  	</div>

  	 <div class="form-group">
  		<label for="modified">modified</label>
  		<input type="text" class="form-control" id="modified" name="modified" value="<?php echo date('d-m-Y') ?>" placeholder="modified">
  	</div>
  	 <div class="form-group">
  		<label for="publish_up">publish_up</label>
  		<input type="text" class="form-control" id="publish_up" value="<?php echo date('d-m-Y') ?>" name="publish_up" placeholder="publish_up">
  	</div>
  	 <div class="form-group">
  		<label for="publish_down">publish_down</label>
  		<input type="text" class="form-control" id="publish_down" value="<?php echo date('d-m-Y') ?>" name="publish_down" placeholder="publish_down">
  	</div>

  	<button type="submit" class="btn btn-primary">Submit</button>
  

	</div>
</div>
</form>