<?php

echo '<h1>Create</h1>';
echo $this->messages();
$form= $this->form;
if ($form instanceof \Zend\Form\Form):
    $form->prepare();
// Assuming the "contact/process" route exists...
    $form->setAttribute('action', $this->url($this->route, array('controller' =>$this->controller, 'action' =>$this->action,'id'=>$this->id))); //'contact/process'));
// Set the method attribute for the form
    $form->setAttribute('method', 'post');
    $form->setAttribute('class', '');
    $this->formElementErrors()
            ->setMessageOpenFormat('<ul class="nav"><li class="erro-obrigatorio">')
            ->setMessageSeparatorString('</li>')->render($form);
    echo $this->form()->openTag($form);
    $linha = '<div class="form-group">
    <label for="#title#">#label#</label>
    #fild#
  </div>';
    $btn=[];
    foreach ($form->getElements() as $element):
        if ($element->getAttribute('type') == "hidden"):
            echo $this->formHidden($element);
        elseif ($element->getAttribute('type') == "submit"):
            $btn[]= $this->formRow($element);
        else:
            $label = $this->translate($element->getLabel());
            $elementArray = array(
                '#fild#' => $this->formRow($element->setLabel("")),
                '#label#' => $label,
                '#title#' => $element->getName(),
            );
            echo str_replace(array_keys($elementArray), array_values($elementArray), $linha);
        endif;

    endforeach;
    $linha = '<a class="btn btn-black" href="%s">
    BTN_VOLTAR_LABEL
  </a><p>';
    $btn[]=  sprintf($linha,$this->url($this->route, array('controller' =>$this->controller, 'action' =>"index")));
    echo implode("", $btn);
    
    echo $this->form()->closeTag();
    else:
        echo "<h1>Nenhum Formulario Enontrado</h1>";
endif;
 echo "<p><p><p>";