<?php echo $this->messages(); ?>
<?=
$this->headTitle(strtoupper(substr($this->controller, 3)));
extract($user);
?>
<section class="content-header">
    <h1>
        Bem Vindo <?php echo $title ?>
    </h1>
    <div class="breadcrumb">
        <ul class="breadcrumbs-item">
            <li>Admin</li>
            <li class="divisor"> / </li>
            <li>Panel</li>
            <li class="divisor"> / </li>
            <li><a href="<?php echo $this->url($route, array('controller' => $controller, 'action' => "index")) ?>"><?= ucfirst($controller) ?> </a></li>
        </ul>
        <?php echo $this->FormHelper()->filterForm($this->filtro); ?>
    </div>
</section>

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="collapse navbar-collapse">
            <?php echo $this->ZFListarHelper()->setNavigation(); ?>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<div id="tabs" class="nav-tabs-custom">
    <ul class="nav nav-tabs">
        <li class=""><a class="tabLink" href="#principal"><?php echo $this->translate('TAB_CONTEUDO_LABEL') ?></a></li>
         <li class=""><a class="tabLink" href="#class"><?php echo $this->translate('TAB_CLASS_LABEL') ?></a></li>
        <li class="pull-right"><i class="ion ion-gear-b"></i></li>
    </ul>
    <div class="tab-content">
        <div id="principal" class="tab-pane ui-state-active">
            <?php
            $button = array(
                'EDITAR' => array('type' => 'a', 'label' => 'EDITAR', 'icone' => 'ion ion-compose', 'action' => 'editar', 'class' => 'green', 'page' => $this->page, 'id' => 'editar'),
                'EXCLUIR' => array('type' => 'a', 'label' => 'EXCLUIR', 'icone' => 'ion ion-ios-trash-outline', 'action' => 'excluir', 'class' => 'blue', 'page' => $this->page, 'id' => 'delete'),
            );
            $html = array();
            $escaper = new \Zend\Escaper\Escaper('utf-8');
            $qtd_col = 4;
            if ($this->data):
                foreach ($this->data as $o) {
                    $value = $o->toArray();
                    $value['description'] = \Base\Model\Check::Words($value['description'], 10);
                    $value['buttons'] = $this->ZFListarHelper()->createBtn($value['id'], $button);
                    $implode = implode("}}&{{", array_keys($value));
                    $keys = explode("&", $implode);
                    if (array_key_exists("images", $value)) {
                        $images = $value['images'];
                        $value['images'] = $this->HtmlTag("img")->setAttributes(array(
                            'alt' => $value['title'],
                            'title' => $value['title'],
                            'src' => "/dist/tim.php?src=/uploads/{$images}&w=370&h=200"
                        ));
                        $value['title'] = \Base\Model\Check::Words($value['title'], 3);
                        $html[] = str_replace(array_values($keys), array_values($value), $this->ZFListarHelper()->setThumbnail($value['id']));
                    } else {
                        $html[] = str_replace(array_values($keys), array_values($value), $this->ZFListarHelper()->setList($value['id']));
                    }
                }
                if ($html):
                    echo $this->HtmlTag('div')->setClass('row')->setText(implode("", $html));
                endif;
            else:
                echo $this->HtmlTag('div')->setClass('trigger trigger_error')->setText("Não exite dados para este modulo");
            endif;
            ?>
            <?php
//            echo $this->paginationControl(
//                    // the paginator object
//                    $this->paginator,
//                    // the scrolling style
//                    'sliding',
//                    // the partial to use to render the control
//                    'partial/paginator.phtml',
//                    // the route to link to when a user clicks a control link
//                    array(
//                'route' => $this->route,
//                'controller' => $this->controller,
//                'action' => 'index',
//                'id' => "0"
//                    )
//            );
            ?>
        </div><!-- /.tab-pane -->
        <div id="class" class="tab-pane">
            <div class="row">
                <div class="box box-full-12">
                    <div class="box">
                        <div class="box-header">
                            <h3 class="box-title">Responsive Hover Table</h3>
                            <div class="box-tools">
                                <div class="input-group">
                                    <div class="input-group-btn">
                                        <a href="<?php echo $this->url('admin/default', array('controller' => 'app', 'action' => 'traduzir')) ?>" class="btn btn-green btn-generate"><i class="ion ion-refresh"> ATUALIZAR TRADUÇÃO</i></a>
                                        <a href="<?php echo $this->url('admin/default', array('controller' => 'app', 'action' => 'adminnavigation')) ?>" class="btn btn-blue btn-generate"><i class="ion ion-refresh"> ATUALIZAR NAVEGAÇÃO</i></a>
                                    </div>
                                </div>
                            </div>
                        </div><!-- /.box-header -->
                        <div class="box-body table-responsive no-padding">
                            <?php
                            foreach ($this->data as $key => $value):
                                extract($value); //echo $this->htmlTable($this->table, $botoes); 
                                $route = "admin/default";
                                $url = array("controller" => "app", "action" => "listarelements", "id" => $id);
                                ?>
                                <div class="list">
                                    <h1 class="list-title"><?= $title ?></h1>
                                    <span class="list-desc"><?= $description; ?> </span>
                                    <small class="list-state"><b>Estado: </b><?= $state; ?></small>
                                    <small class="list-created"><b>Criado Em: </b><?= $created->format("d/m/Y"); ?> </small>
                                    <small class="list-autor"><b>Autor: </b><?= $editorBy; ?> </small>
                                    <div class="list-footer">
                                        <?php if ($tipoModulo == 2 || $tipoModulo == 4): ?>
                                            <a href="<?php echo $this->url($route, array('controller' => 'app', 'action' => 'listarelements', 'id' => $id)); ?>" class="btn btn-green btn-xs fancybox" data-fancybox-type="iframe" title="Editar Elementos">
                                                <i class="ion ion-edit"></i>
                                                <span class="hidden-xs"> Editar</span></a>

                                            <a href="<?php echo $this->url($route, array('controller' => 'app', 'action' => 'createentity', 'id' => $id)); ?>" class="btn btn-blue btn-xs btn-generate" title="Gerar Entidades"><i class="ion ion-checkmark"> </i>
                                                <span class="hidden-xs"> G. Entity!</span></a>
                                        <?php endif; ?>

                                        <?php if ($tipoModulo == 1 || $tipoModulo == 3): ?>
                                            <a href="<?php echo $this->url($route, array('controller' => 'app', 'action' => 'createmodule', 'id' => $id)); ?>" class="btn btn-yellow btn-xs btn-generate" title="Gerar Modulos"><i class="ion ion-checkmark"></i>
                                                <span class="hidden-xs">  G. Module!</span></a>

                                            <a href="<?php echo $this->url($route, array('controller' => 'app', 'action' => 'createconfig', 'id' => $id)); ?>" class="btn btn-blue btn-xs btn-generate" title="Gerar Configuração"><i class="ion ion-checkmark"></i>
                                                <span class="hidden-xs">  G. Config!</span></a>
                                        <?php endif; ?>

                                        <?php if ($tipoModulo == 2 || $tipoModulo == 4): ?>
                                            <a href="<?php echo $this->url($route, array('controller' => 'app', 'action' => 'createcontroller', 'id' => $id)); ?>" class="btn btn-red btn-xs btn-generate" title="Gerar Controles"><i class="ion ion-checkmark"> </i>
                                                <span class="hidden-xs"> G. Controller!</span></a>
                                        <?php endif; ?>
                                        <?php if ($tipoModulo == 2 || $tipoModulo == 4): ?>
                                            <a href="<?php echo $this->url($route, array('controller' => 'app', 'action' => 'createservice', 'id' => $id)); ?>" class="btn btn-yellow btn-xs btn-generate" title="Gerar Services"><i class="ion ion-checkmark"> </i>
                                                <span class="hidden-xs"> G. Serviçe!</span></a>

                                            <a href="<?php echo $this->url($route, array('controller' => 'app', 'action' => 'createform', 'id' => $id)); ?>" class="btn btn-info btn-xs btn-generate" title="Gerar Formulario"><i class="ion ion-checkmark"></i>
                                                <span class="hidden-xs">  G. Form!</span></a>
                                        <?php endif; ?>

                                        <?php if ($tipoModulo == 2 || $tipoModulo == 3): ?>
                                            <a href="<?php echo $this->url($route, array('controller' => 'app', 'action' => 'createfactory', 'id' => $id)); ?>" class="btn btn-green btn-xs btn-generate" title="Gerar Fabricas"><i class="ion ion-checkmark"></i>
                                                <span class="hidden-xs">  G. Factory!</span></a>
                                        <?php endif; ?>

                                        <?php if ($tipoModulo == 2 || $tipoModulo == 4): ?>
                                            <a href="<?php echo $this->url($route, array('controller' => 'app', 'action' => 'deletaarquivo', 'id' => $id)); ?>" class="btn btn-red btn-xs btn-generate" title="Deletar Arquivos Do Modulo"><i class="ion ion-trash-a"></i>
                                                <span class="hidden-xs"> Deletar!</span></a> 
                                        <?php endif; ?>

                                    </div>
                                </div>
                            <?php endforeach; ?>
                        </div><!-- /.box-body -->
                    </div><!-- /.box -->
                </div>
            </div>
            <div class="box box-full-12">
                <div class="box box-default">
                    <div class="box-header with-border">
                        <h3 class="box-title">Gerar um arquivo unico</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form role="form" id="generateArquivo" action="<?php echo $this->url('admin/default', array('controller' => 'app', 'action' => 'arquivounico')) ?>" method="POST">
                        <div class="box-body">
                            <div class="form-group">
                                <label for="alias">Nome Do Modulo</label>
                                <input type="text"  required="required" placeholder="Nome do modulo" id="alias" name="alias" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="alias">Sub Modulo</label>
                                <select name="submodule" required="required" class="form-control" id="submodule">
                                    <option value="Entity">Entidade</option>
                                    <option disabled="disabled" value="Form">Formulario</option>
                                    <option disabled="disabled" value="Controller">Controller</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="arquivo">Nome do arquivo</label>
                                <input type="text"  required="required" placeholder="Nome do Arquivo" id="arquivo" name="arquivo" class="form-control">
                            </div>
                        </div>
                        <!-- /.box-body -->
                        <div class="box-footer">
                            <button class="btn btn-blue" type="submit">Gerar Arquivo</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
          <div class="clear"></div>
    </div><!-- /.tab-content -->
</div>


<script>
    $(function () {

        $("#created, #publish_down").datetimepicker({
            timepicker: false,
            format: 'd-m-Y',
            onChangeDateTime: function (dp, $input) {
                //alert($input.val());
            }
        });
        $.datetimepicker.setLocale('pt-BR');
    });
</script>
