
<?php

echo '<h1>Create</h1>';
$form = $this->form;
$form->prepare();
// Assuming the "contact/process" route exists...
$form->setAttribute('action', $this->url('auth/default', array('controller' => 'admin', 'action' => 'create'))); //'contact/process'));
// Set the method attribute for the form
$form->setAttribute('method', 'post');
$form->setAttribute('class', '');
$this->formElementErrors()
        ->setMessageOpenFormat('<ul class="nav"><li class="erro-obrigatorio">')
        ->setMessageSeparatorString('</li>')->render($form);
echo $this->form()->openTag($form);
$linha = '<div class="form-group">
    <label for="#title#">#label#</label>
    #fild#
  </div>';
foreach ($form->getElements() as $element):
    if($element->getAttribute('type')=="cidade"){
        
    }
    if ($element->getAttribute('type') == "hidden"):
        echo $this->formHidden($element);
    elseif ($element->getAttribute('type') == "submit"):
        echo $this->formRow($element);
    else:
        $label = $this->translate($element->getLabel());
        $elementArray = array(
            '#fild#' => $this->formRow($element->setLabel("")),
            '#label#' => $label,
            '#title#' => $element->getName(),
        );
        echo str_replace(array_keys($elementArray), array_values($elementArray), $linha);
    endif;

endforeach;

echo $this->form()->closeTag();
