<h1><?php echo $this->translate('Area Retrieve') ?></h1>
<?php
echo $this->messages();
// view helper
if ($user = $this->user):
   
    echo 'Logged in as ' . $this->escapeHtml($user->title);
    ?>
    | <a href="<?php echo $this->url('auth/default', array('controller' => 'login', 'action' => 'logout')); ?>"><?php echo $this->translate('Logout'); ?></a> | 
      <a href="<?php echo $this->url($this->route, array('controller' => 'admin', 'action' => 'create')); ?>"><?php echo $this->translate('Register'); ?></a> 
    <?php else:
    ?>
    <p>
        <a href="<?php echo $this->url($this->route, array('controller' => 'registration', 'action' => 'registration')); ?>"><?php echo $this->translate('Register'); ?></a> |
        <a href="<?php echo $this->url($this->route); ?>"><?php echo $this->translate('Login'); ?></a>
    </p>
<?php endif; ?>

<?php if ($rowset): ?>
    <table class="table table-condensed">
        <tr>
            <th>usr_id</th>
            <th>usr_name</th>
            <th>usr_email</th>
        </tr>
        <?php
        foreach ($rowset as $row) {
            ?>
            <tr>
                <td><?php echo $row->getId(); ?></td>
                <td><?php echo $row->getTitle(); ?></td>
                <td><?php echo $row->getEmail(); ?></td>
                <td><a href="<?php echo $this->url('auth/default', array('controller' => 'admin', 'action' => 'update', 'id' => $row->getId())); ?>">Edit</a></td>
                <td><a href="<?php echo $this->url('auth/default', array('controller' => 'admin', 'action' => 'delete', 'id' => $row->getId())); ?>" onclick="return confirm('Do you rely want to delete the record;')">Delete</a></td>
            </tr>
            <?php
        }
        ?>
    </table>
    <?php
 endif;