<?php echo $this->doctype();
?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
     <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
               ->prependStylesheet($this->basePath('/home_assets/css/style.css'))
                ->prependStylesheet($this->basePath('/admin_assets/css/forms-default.css'))
                ->prependStylesheet($this->basePath('/admin_assets/css/ionicons.min.css'))
                ->prependStylesheet($this->basePath('/admin_assets/css/boot.css'))
        ?>

    </head>
    <body>
        <main class="container main-container">
      
        <?php echo $this->content;?>
        <!-- /.content -->
        <!-- ============================================================= FOOTER ============================================================= -->
        <!--seção temática-->
       
        <footer class="container copy footer-fixed">
                <div class="content-small">
                    <p class="plast">&copy; <?= date('Y'); ?> - SIGA-Sistemas, Todos Os Direitos Reservados!</p>
                </div>
        </footer>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                 ->prependFile($this->basePath('/admin_assets/js/scripts.js'))
                ->prependFile($this->basePath('/admin_assets/js/jquery.form.min.js'))
                ->prependFile($this->basePath('/admin_assets/js/jQuery-2.1.4.min.js'))
                ->prependFile($this->basePath('/admin_assets/js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('/admin_assets/js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',));?>
        <?php echo $this->inlineScript() ?>
       
    </main>
    </body>
</html>
