<?php echo $this->doctype();
$user = $this->UserIdentity();
$config = $this->CacheHelper()->getItem('companies');
extract($config);
?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
     <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
               ->prependStylesheet($this->basePath('/home_assets/css/style.css'))
                ->prependStylesheet($this->basePath('/admin_assets/css/forms-default.css'))
                ->prependStylesheet($this->basePath('/admin_assets/css/ionicons.min.css'))
                ->prependStylesheet($this->basePath('/admin_assets/css/boot.css'))
        ?>

    </head>
    <body>
        <main class="container main-container">
       <header class="bg-gray main_header">
           <div class="mobile-btn open">
               
           </div>
            <div>
                 <a title="Home" href="./" class="main_logo fl-left"><h1 class="fontzero">SIGA-SMART! Sistema Integrado de Gerenciamento e Administração.</h1> 
                      <img src="/dist/tim.php?src=/admin_assets/images/panel-siga-transparente.png&w=100&h=50" alt="SIGA-SMART! Sistema Integrado de Gerenciamento e Administração.">
                   
                </a>
              <?php //echo $this->navigation('navigation_site')->menu()->setUlClass('main_nav transition fl-right'); //->setPartial('partial/navigationSite.phtml');   
              $baner="/img/banner"; ?>
                <div class="clear"></div>
            </div>
        </header> 
    
        <?php echo $this->content;?>
        <!-- /.content -->
        <!-- ============================================================= FOOTER ============================================================= -->
        <!--seção temática-->
       
        <footer class="container copy">
                <div class="content-small">
                    <p class="plast">&copy; <?= date('Y'); ?> - SIGA-Sistemas, Todos Os Direitos Reservados!</p>
                </div>
        </footer>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                 ->prependFile($this->basePath('/admin_assets/js/scripts.js'))
                ->prependFile($this->basePath('/admin_assets/js/jquery.form.min.js'))
                ->prependFile($this->basePath('/admin_assets/js/jQuery-2.1.4.min.js'))
                ->prependFile($this->basePath('/admin_assets/js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('/admin_assets/js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',));?>
        <?php echo $this->inlineScript() ?>
        <input type="hidden" id="longetude" value="<?= $longetude ?>">
        <input type="hidden" id="latitude" value="<?= $latitude ?>">
        <img style="display: none" src="/admin_assets/img/load.gif"/>
    </main>
    </body>
</html>
