<?php
echo $this->doctype();
$usuario = $this->UserIdentity();
extract($usuario);
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('/admin_assets/css/forms-default.css'))
                ->prependStylesheet($this->basePath('/admin_assets/css/style.css'))
                ->prependStylesheet($this->basePath('/admin_assets/css/widgets.css'))
                ->prependStylesheet($this->basePath('/admin_assets/css/ionicons.min.css'))
                ->prependStylesheet($this->basePath('/admin_assets/css/jquery.datetimepicker.css'))
                ->prependStylesheet($this->basePath('/admin_assets/css/boot.css'))
        ?>
    </head>
    <body>
        <div id="alert" class="trigger box-carregando">
        </div>
        <div class="trigger trigger_info carregando">

        </div>
        <section class="container main-header">
            <div class="main-header-top-left header_green">
                <picture alt="Layout Admin">      
                    <source media="(min-width: 1px)" srcset="/admin_assets/images/panel-siga-transparente.png"/>                   
                    <img  class="logo" src="/admin_assets/images/panel-siga-transparente.png" alt="Layout Admin" title="Layout Admin"/>
                </picture>
            </div>
            <div class="main-header-top-right header_green">
                <span class="mobile-action b-r-full"></span>
                <div class="nav-profile">
                    <ul class="profile">
                        <li  class="profile-item">
                            <a href="#" class="profile-link">
                                <img src="/admin_assets/img/no_avatar.jpg" class="img-profile-item b-r-full">
                                <span class="profile-open">Claudio Camos</span> </a>
                            <ul class="profile-sub">
                                <li class="profile-sub-avatar"><a href="#"> <img src="/admin_assets/img/no_avatar.jpg" class="img-profile-item b-r-full"></a></li>
                                <li class="profile-sub-info"><a href="#"><?= $title ?></a></li>
                                <li class="profile-sub-date"><a href="#"><?php echo date("m", strtotime($created)); ?>, <?php echo date("Y", strtotime($created)); ?></a></li>
                                <li class="profile-sub-profile"><a class="btn btn-blue" href="<?php echo $this->url('auth/default', array('controller' => 'registration', 'action' => 'profileupdate')); ?>">M. Conta</a></li>
                                <li class="profile-sub-logout"><a class="btn btn-red" href="<?php echo $this->url('auth/default', array('controller' => 'login', 'action' => 'logout')); ?>">Sair Do Sist.</a></li>
                            </ul>
                        </li>
                    </ul>
                    <div class="clear"></div>
                </div>
            </div>

        </section>
        <!-- container main -->
        <main class="container main">
            <!-- =============================================== -->
            <!-- Left side column. contains the sidebar -->
            <aside class="content-left transition">
                <header class="sidebar-user">
                    <h1 class="sidebar-user-img">
                        <img src="/admin_assets/img/no_avatar.jpg" class="img-profile-item b-r-full">
                    </h1>
                    <sapn class="sidebar-online">
                        <?php echo $title; ?>
                        <p><i class="on b-r-full"></i> Online</p>
                    </sapn>
                </header>
                <ul class="main-sidebar">
                    <?php echo $this->navigation('navigation')->menu()->setPartial('partial/navigation.phtml'); ?>
                </ul>

                <!-- /.sidebar -->
            </aside>

            <!-- =============================================== -->

            <section class="content-right bg-body transition">
                <div class="main-content">
                    <!-- Content Header (Page header) -->
                    <?php echo $this->content; ?>
                    <div class="clear"></div>
                    </div>
            </section>
            <footer class="main-footer">
                <div class="fl-right hidden-xs">
                    <b>Version</b> 2.3.0
                </div>
                <strong>Copyright &copy; 2014-2015 <a href="http://almsaeedstudio.com">Almsaeed Studio</a>.</strong> All rights reserved.
            </footer>
        </main> <!-- /container -->

        <!-- Scripts -->
        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('/admin_assets/js/geral/upload.js'))
                ->prependFile($this->basePath('/admin_assets/js/Manager.js'))
                ->prependFile($this->basePath('/admin_assets/js/App.js'))
                ->prependFile($this->basePath('/admin_assets/js/Dlls.js'))
                ->prependFile($this->basePath('/admin_assets/js/SIGAMessages.js'))
                ->prependFile($this->basePath('/admin_assets/js/jquery.form.min.js'))
                ->prependFile($this->basePath('/admin_assets/js/geral/jquery.datetimepicker.full.min.js'))
                ->prependFile($this->basePath('/admin_assets/js/jquery.min.js'))
                ->prependFile($this->basePath('/admin_assets/s/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('/admin_assets/js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',));
        ?>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
