<div class="box&#x20;box-full-12&#x20;box-mini-06&#x20;&#x20;box-small-06&#x20;box-medium-04&#x20;box-large-04&#x20;col-box-list">
    <div class="widgets-box">
        <div class="box-header&#x20;box-default">
            <i class="ion&#x20;ion-android-open"></i>
            <h2 class="box-title">{{title}}</h2>
            <br />
            <small class="fl-left">CRIADO EM: {{created}}</small><small class="fl-right"> POR: {{editor_by}}</small>
        </div>
        <div class="box-body">
            <p class="box-description">
            <div class="box-list&#x20;list-email"><i class="ico&#x20;ico-email"></i><span class="label-list&#x20;label-list-email">email :</span><span class="data-list&#x20;data-list-email">{{email}}</span>
            </div>
             <div class="box-list&#x20;list-facebook"><i class="ico&#x20;ico-facebook"></i><span class="label-list&#x20;label-list-facebook">facebook :</span><span class="data-list&#x20;data-list-facebook">{{facebook}}</span>
            </div>
             <div class="box-list&#x20;list-twitter"><i class="ico&#x20;ico-twitter"></i><span class="label-list&#x20;label-list-twitter">twitter :</span><span class="data-list&#x20;data-list-twitter">{{twitter}}</span>
            </div>
             <div class="box-list&#x20;list-phone"><i class="ico&#x20;ico-phone"></i><span class="label-list&#x20;label-list-phone">phone :</span><span class="data-list&#x20;data-list-phone">{{phone}}</span>
            </div>
            <div class="box-list&#x20;list-whatsapp"><i class="ico&#x20;ico-whatsapp"></i><span class="label-list&#x20;label-list-whatsapp">whatsapp :</span><span class="data-list&#x20;data-list-whatsapp">{{whatsapp}}</span>
            </div>
            <div class="box-list&#x20;list-description"><i class="ico&#x20;ico-description"></i><span class="label-list&#x20;label-list-description">description :</span><span class="data-list&#x20;data-list-description">{{description}}</span></div>
            <div class="box-list&#x20;list-alias"><i class="ico&#x20;ico-alias"></i><span class="label-list&#x20;label-list-alias">alias :</span><span class="data-list&#x20;data-list-alias">{{alias}}</span>
            </div>
            <div class="box-list&#x20;list-state">
                <i class="ico&#x20;ico-state"></i><span class="label-list&#x20;label-list-state">state :</span>
                <span class="data-list&#x20;data-list-state">{{state}}</span></div>
            <div class="box-list&#x20;list-publish_up"><i class="ico&#x20;ico-publish_up"></i><span class="label-list&#x20;label-list-publish_up">publish_up :</span><span class="data-list&#x20;data-list-publish_up">{{publish_up}}</span></div>
            <div class="box-list&#x20;list-publish_down"><i class="ico&#x20;ico-publish_down"></i><span class="label-list&#x20;label-list-publish_down">publish_down :</span><span class="data-list&#x20;data-list-publish_down">{{publish_down}}</span></div>
            </p>
        </div>
        <div class="box-footer">{{buttons}}</div>
    </div>
</div>