<?php
/* @var $container Zend\Navigation\Navigation */
$container = $this->container;

if ($container):
    ?>

    <?php foreach ($container as $page): ?>
        <?php if (!$this->navigation()->accept($page)) continue; ?>
        <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
        <?php $hasChildren = $page->hasPages() ?>
        <?php
        if ($hasChildren):
            //check if access is allowed at least one item
            $access = false;
            foreach ($page->getPages() as $child) {
                if ($this->navigation()->accept($child) && $child->get("separator") !== true) {
                    $access = true;
                }
            }
            if ($access) :
                ?>
                <li class="sidebar-item treeview <?php if ($page->isActive(true)) echo ' active' ?>">
                    <a href="#">
                        <?php if ($page->get("icone") !== ""): ?>
                            <i class="<?php echo $page->get("icone"); ?>"></i>
                <?php endif; ?>
                        <span><?php echo $this->escapeHtml($this->translate($page->getLabel(), $this->navigation($container)->getTranslatorTextDomain())); ?></span>

                    </a>
                    <ul class="sidebar-sub">
                        <?php foreach ($page->getPages() as $child): ?>
                            <?php if (!$this->navigation()->accept($child)) continue; ?>
                            <?php if ($child->get("separator") === true): ?>
                                <li class="divider"></li>
                                <?php
                                continue;
                            endif;
                            ?>
                            <li class="sidebar-sub-item <?php if ($child->isActive()) echo ' active' ?>">
                                <a 
                                    href="<?php echo $child->getHref() ?>"
                                    <?php if ($child->getTarget() != ""): ?>
                                        target="<?php echo $child->getTarget(); ?>"
                                        <?php endif; ?> >
                                    <?php if ($child->get("icone") !== ""): ?>
                                        <i class="<?php echo $child->get("icone"); ?>"></i>
                    <?php endif; ?>
                                    <span><?php echo $this->escapeHtml($this->translate($child->getLabel(), $this->navigation($container)->getTranslatorTextDomain())); ?></span>
                                </a>
                            </li>
                <?php endforeach ?>
                    </ul>
                </li>  
            <?php endif; ?>
        <?php else: ?>
            <li class="sidebar-item <?php if ($page->isActive()) echo ' active' ?>">
                <a 
                    href="<?php echo $page->getHref() ?>"
                    <?php if ($page->getTarget() != ""): ?>
                        target="<?php echo $page->getTarget(); ?>"
                        <?php endif; ?> >
                    <?php if ($page->get("icone") !== ""): ?>
                        <i class="<?php echo $page->get("icone"); ?>"></i>
            <?php endif; ?>
                    <span><?php echo $this->escapeHtml($this->translate($page->getLabel(), $this->navigation($container)->getTranslatorTextDomain())); ?></span>
                </a>
            </li>

        <?php endif ?>
    <?php endforeach ?>

    <?php


endif;