<fildset><legend>FORMULARIO DE MANUTENÇÃO</legend><div class="box&#x20;box-full-12&#x20;box-medium-06&#x20;box-large-08">
<div class="widgets-box"><div class="box-header&#x20;box-default"><i class="ion&#x20;ion-clipboard"></i><h3 class="box-title">GERAL</h3></div>
<div class="box-body">
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12">{{title}}#title#</div>
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-06">{{conta_tipo}}#conta_tipo#</div>

<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-06">{{situacao}}#situacao#</div>

<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-04 banco">{{banco_id}}#banco_id#</div>

<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-06&#x20;box-large-03 banco">{{tipo}}#tipo#</div>

<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-06&#x20;box-large-02 banco">{{agencia}}#agencia#</div>

<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-03 banco">{{conta}}#conta#</div>

<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-05 banco">{{gerente}}#gerente#</div>
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-06&#x20;box-large-05 banco">{{phone}}#phone#</div>
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-06&#x20;box-large-03">{{saldo}}#saldo#</div>
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-09">{{alias}}#alias#</div>

<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12">{{description}}#description#</div>
#asset_id##empresa##created_by##modified_by##ordering##modified##security#</div><div class="box-footer"><div class="pull-right">#save##save_copy#<a class="btn btn-black" href="/fluxo-caixa/bs-contas/index"><?php echo $this->translate('BTN_VOLTAR_LABEL')?></a><p></div></div></div></div><div class="box&#x20;box-full-12&#x20;box-medium-06&#x20;box-large-04"><div class="widgets-box"><div class="box-header&#x20;box-default"><i class="ion&#x20;ion-clipboard"></i><h3 class="box-title">CONTROLES</h3></div><div class="box-body"><div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12">{{id}}#id#</div>
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12">{{codigo}}#codigo#</div>
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12">{{state}}#state#</div>
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12">{{access}}#access#</div></div></div></div><div class="box&#x20;box-full-12&#x20;box-medium-06&#x20;box-large-04"><div class="widgets-box"><div class="box-header&#x20;box-default"><i class="ion&#x20;ion-clipboard"></i><h3 class="box-title">DATAS</h3></div><div class="box-body"><div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12">{{created}}<div class="input-group-addon"></div>#created#</div>
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12">{{publish_up}}<div class="input-group-addon"></div>#publish_up#</div>
<div class="form-group&#x20;box&#x20;box-full-12&#x20;box-medium-12&#x20;box-large-12">{{publish_down}}<div class="input-group-addon"></div>#publish_down#</div></div></div></div></fildset>