<h1>Upload</h1>
<fieldset>
    <legend>Files list</legend>
    <div id="files" data-content-url="<?php echo $this->url('upload/default',array('controller'=>'upload','action'=>'list')) ?>">
        <?php echo $this->partial('/list'); ?>
    </div>
</fieldset>
<p>
<fieldset>
    <legend>Upload new files</legend>
    <form name="uploadFile" id="uploadFiles" class="uploadFile" method="post"
          action="<?php echo $this->url('upload/default',array('controller'=>'upload','action'=>'uploads')) ?>" enctype="multipart/form-data">
         <input type="file" name="files[]" multiple>
        <button type="submit" class="btn btn-primary">Upload files</button>
        
    </form>
</fieldset>
<p>
<hr>
<fieldset>
    <legend>Upload new file</legend>
    <form name="uploadFile" class="uploadFile" id="uploadFile" method="post"
          action="<?php echo $this->url('upload/default',array('controller'=>'upload','action'=>'upload')) ?>" enctype="multipart/form-data">
        <input type="file" name="files">
        <button type="submit" class="btn btn-primary">Upload file</button>
    </form>
</fieldset>
