<h1>Upload</h1>
<fieldset>
    <legend>Files list</legend>
    <div id="files" data-content-url="<?php echo $this->url('upload/default', array('controller' => 'upload', 'action' => 'list')) ?>">
        <?php echo $this->partial('/list'); ?>
    </div>
</fieldset>
<p>
<fieldset>
    <legend>Upload new files</legend>
    <?php
    // filename : module/Test/view/test/profile/add.phtml
    $form = $this->form;
    $form->setAttribute('action', $this->url('upload/default', array('controller' => 'upload', 'action' => 'uploads')));
    $form->prepare();
    $form->get('files')->setAttribute('multiple', TRUE);
    $form->get('files')->setAttribute('id', 'files');
    $form->setAttribute('id', 'uploadFiles');
    $form->setAttribute('enctype', 'multipart/form-data');
    $form->setAttribute('name', 'uploadFiles');
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();
    ?>

</fieldset>
<p>
<hr>
<fieldset>
    <legend>Upload new file</legend>
    <?php
    // filename : module/Test/view/test/profile/add.phtml
    $form = $this->form;
    $form->setAttribute('action', $this->url('upload/default', array('controller' => 'upload', 'action' => 'upload')));
    $form->prepare();
    $form->get('files')->setAttribute('multiple', FALSE);
    $form->get('files')->setAttribute('id', 'file');
    $form->setAttribute('id', 'uploadFile');
    $form->setAttribute('enctype', 'multipart/form-data');
    $form->setAttribute('name', 'uploadFile');
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();
    ?>

</fieldset>
