<?php
$filesList = $this->files->getFiles();
if (!isset($filesList) || count($filesList) === 0):
    ?>
    <div class="alert alert-warning text-center">
        Files dir is empty
    </div><?php else:
    ?>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Extension</th>
                <th>Size</th>
                <th>MimeType</th>
                <th>#</th>
            </tr>
        </thead>
        <tbody><?php
            /** @var SplFileInfo $file */
            foreach ($filesList as $file):?>
                <tr>
                    <td><?php if (array_search($file['mimetype'], $this->files->getOptions()->getFileAccept())): ?>
                            <?= $file['title']; ?>
                        <?php elseif (array_search($file['mimetype'], $this->files->getOptions()->getMidiaAccept())): ?>
                            <audio controls>
                                <source src="/dist/<?= $file['title']; ?>" type="audio/mpeg">
                                Your browser does not support the audio element.
                            </audio> 
                        <?php else: ?>
                            <img alt="[<?= $file['title']; ?>]" title="<?= $file['title']; ?>" src="/dist/tim.php?src=/dist/<?php echo $file['title'] ?>&w=100&h=100">
                        <?php endif; ?>
                    </td>
                   <td><?php echo $file['extension'] ?></td>
                    <td><?php echo $file['size'] ?></td>
                    <td><?php echo $file['mimetype'] ?></td>
                    <td><a href="<?php echo $this->url('upload/default', array('controller' => 'upload', 'action' => 'remove','id'=>$file['id'])) ?>" class="btn btn-blue remove-file" title="Excluir Resgistro">EXCLUIR</a></td>
                </tr><?php endforeach; ?>
        </tbody>
    </table><?php
endif;