 <div class="box login-box">
      <div class="main-login-header">
        <a href="<?php echo $this->url('admin')?>"><img src="/img/logo-siga-q.png"></a>
      </div><!-- /.login-logo -->
      <div class="main-login-box login-box-body">
        <p class="trigger trigger_info">Faça login para começar a sua sessão</p>
         <?php
            echo $this->id;
            $form = $this->form;
            $form->setAttribute('action', $this->url('auth/default', array('controller'=>'auth','action' => 'authenticate')));
            $form->prepare();
            echo $this->form()->openTag($form);?>
          <div class="form-group has-feedback">
            <?php echo $this->formEmail($form->get('email')); ?>
            <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
          </div>
          <div class="form-group has-feedback">
            <?php echo $this->formPassword($form->get('password')); ?>
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
          </div>
          <div class="row">
            <div class="box box-full-07">
              <div class="checkbox icheck">
                <label>
                  <?php echo $this->formCheckbox($form->get('rememberme')); ?> Lembre-me
                </label>
              </div>
            </div><!-- /.col -->
            <div class="box box-full-05">
              <button type="submit" class="btn btn-green fl-right">ACESSAR!</button>
            </div><!-- /.col -->
          </div>
         <?php echo $this->form()->closeTag(); ?>
        <?php echo $this->messages(); ?>
        <p>
        <a href="../">&larrhk; Voltar para Site!</a> &nbsp;&nbsp;&nbsp; 
        <a  href="<?php echo $this->url('auth/default', array('controller'=>'auth','action' => 'rememberme')) ?>">Recuperar Minha Senha</a><br>
        
      </div><!-- /.login-box-body -->
    </div><!-- /.login-box -->
