<div class="box&#x20;box-full-12&#x20;box-mini-06&#x20;&#x20;box-small-06&#x20;box-medium-04&#x20;box-large-04&#x20;col-box-list">
<div class="widgets-box">
<div class="box-header&#x20;box-default"><i class="ion&#x20;ion-android-open"></i>
<h3 class="box-title">{{title}}</h3>
<br />
<small class="fl-left"><?php echo $this->translate('CRIADO EM: ');?>{{created}}</small><small class="fl-right"><?php echo $this->translate(' POR: ');?>{{editor_by}}</small>
</div>
<div class="box-body">
<p class="box-description">
<div class="box-list&#x20;list-empresa">
<i class="ico&#x20;ico-empresa"></i>
<span class="label-list&#x20;label-list-empresa">
<?php echo $this->translate('empresa');?> :
</span>
<span class="data-list&#x20;data-list-empresa">{{empresa}}</span>
</div>
<div class="box-list&#x20;list-tipo">
<i class="ico&#x20;ico-tipo"></i>
<span class="label-list&#x20;label-list-tipo">
<?php echo $this->translate('tipo');?> :
</span>
<span class="data-list&#x20;data-list-tipo">{{tipo}}</span>
</div>
<div class="box-list&#x20;list-cnpj">
<i class="ico&#x20;ico-cnpj"></i>
<span class="label-list&#x20;label-list-cnpj">
<?php echo $this->translate('cnpj');?> :
</span>
<span class="data-list&#x20;data-list-cnpj">{{cnpj}}</span>
</div>
<div class="box-list&#x20;list-rg">
<i class="ico&#x20;ico-rg"></i>
<span class="label-list&#x20;label-list-rg">
<?php echo $this->translate('rg');?> :
</span>
<span class="data-list&#x20;data-list-rg">{{rg}}</span>
</div>
<div class="box-list&#x20;list-ie">
<i class="ico&#x20;ico-ie"></i>
<span class="label-list&#x20;label-list-ie">
<?php echo $this->translate('ie');?> :
</span>
<span class="data-list&#x20;data-list-ie">{{ie}}</span>
</div>
<div class="box-list&#x20;list-phone">
<i class="ico&#x20;ico-phone"></i>
<span class="label-list&#x20;label-list-phone">
<?php echo $this->translate('phone');?> :
</span>
<span class="data-list&#x20;data-list-phone">{{phone}}</span>
</div>
<div class="box-list&#x20;list-whatsapp">
<i class="ico&#x20;ico-whatsapp"></i>
<span class="label-list&#x20;label-list-whatsapp">
<?php echo $this->translate('whatsapp');?> :
</span>
<span class="data-list&#x20;data-list-whatsapp">{{whatsapp}}</span>
</div>
<div class="box-list&#x20;list-email">
<i class="ico&#x20;ico-email"></i>
<span class="label-list&#x20;label-list-email">
<?php echo $this->translate('email');?> :
</span>
<span class="data-list&#x20;data-list-email">{{email}}</span>
</div>
<div class="box-list&#x20;list-facebook">
<i class="ico&#x20;ico-facebook"></i>
<span class="label-list&#x20;label-list-facebook">
<?php echo $this->translate('facebook');?> :
</span>
<span class="data-list&#x20;data-list-facebook">{{facebook}}</span>
</div>
<div class="box-list&#x20;list-twitter">
<i class="ico&#x20;ico-twitter"></i>
<span class="label-list&#x20;label-list-twitter">
<?php echo $this->translate('twitter');?> :
</span>
<span class="data-list&#x20;data-list-twitter">{{twitter}}</span>
</div>
<div class="box-list&#x20;list-cidade">
<i class="ico&#x20;ico-cidade"></i>
<span class="label-list&#x20;label-list-cidade">
<?php echo $this->translate('cidade');?> :
</span>
<span class="data-list&#x20;data-list-cidade">{{cidade}}</span>
</div>
<div class="box-list&#x20;list-cep">
<i class="ico&#x20;ico-cep"></i>
<span class="label-list&#x20;label-list-cep">
<?php echo $this->translate('cep');?> :
</span>
<span class="data-list&#x20;data-list-cep">{{cep}}</span>
</div>
<div class="box-list&#x20;list-bairro">
<i class="ico&#x20;ico-bairro"></i>
<span class="label-list&#x20;label-list-bairro">
<?php echo $this->translate('bairro');?> :
</span>
<span class="data-list&#x20;data-list-bairro">{{bairro}}</span>
</div>
<div class="box-list&#x20;list-endereco">
<i class="ico&#x20;ico-endereco"></i>
<span class="label-list&#x20;label-list-endereco">
<?php echo $this->translate('endereco');?> :
</span>
<span class="data-list&#x20;data-list-endereco">{{endereco}}</span>
</div>
<div class="box-list&#x20;list-credito">
<i class="ico&#x20;ico-credito"></i>
<span class="label-list&#x20;label-list-credito">
<?php echo $this->translate('credito');?> :
</span>
<span class="data-list&#x20;data-list-credito">{{credito}}</span>
</div>
<div class="box-list&#x20;list-description">
<i class="ico&#x20;ico-description"></i>
<span class="label-list&#x20;label-list-description">
<?php echo $this->translate('description');?> :
</span>
<span class="data-list&#x20;data-list-description">{{description}}</span>
</div>
<div class="box-list&#x20;list-images">
<i class="ico&#x20;ico-images"></i>
<span class="label-list&#x20;label-list-images">
<?php echo $this->translate('images');?> :
</span>
<span class="data-list&#x20;data-list-images">{{images}}</span>
</div>
<div class="box-list&#x20;list-ordering">
<i class="ico&#x20;ico-ordering"></i>
<span class="label-list&#x20;label-list-ordering">
<?php echo $this->translate('ordering');?> :
</span>
<span class="data-list&#x20;data-list-ordering">{{ordering}}</span>
</div>
<div class="box-list&#x20;list-state">
<i class="ico&#x20;ico-state"></i>
<span class="label-list&#x20;label-list-state">
<?php echo $this->translate('state');?> :
</span>
<span class="data-list&#x20;data-list-state">{{state}}</span>
</div>
<div class="box-list&#x20;list-created_by">
<i class="ico&#x20;ico-created_by"></i>
<span class="label-list&#x20;label-list-created_by">
<?php echo $this->translate('created_by');?> :
</span>
<span class="data-list&#x20;data-list-created_by">{{created_by}}</span>
</div>
<div class="box-list&#x20;list-modified_by">
<i class="ico&#x20;ico-modified_by"></i>
<span class="label-list&#x20;label-list-modified_by">
<?php echo $this->translate('modified_by');?> :
</span>
<span class="data-list&#x20;data-list-modified_by">{{modified_by}}</span>
</div>
<div class="box-list&#x20;list-alias">
<i class="ico&#x20;ico-alias"></i>
<span class="label-list&#x20;label-list-alias">
<?php echo $this->translate('alias');?> :
</span>
<span class="data-list&#x20;data-list-alias">{{alias}}</span>
</div>
<div class="box-list&#x20;list-modified">
<i class="ico&#x20;ico-modified"></i>
<span class="label-list&#x20;label-list-modified">
<?php echo $this->translate('modified');?> :
</span>
<span class="data-list&#x20;data-list-modified">{{modified}}</span>
</div>
<div class="box-list&#x20;list-publish_up">
<i class="ico&#x20;ico-publish_up"></i>
<span class="label-list&#x20;label-list-publish_up">
<?php echo $this->translate('publish_up');?> :
</span>
<span class="data-list&#x20;data-list-publish_up">{{publish_up}}</span>
</div>
<div class="box-list&#x20;list-publish_down">
<i class="ico&#x20;ico-publish_down"></i>
<span class="label-list&#x20;label-list-publish_down">
<?php echo $this->translate('publish_down');?> :
</span>
<span class="data-list&#x20;data-list-publish_down">{{publish_down}}</span>
</div></p></div>
<div class="box-footer">{{buttons}}</div>
</div>
</div>